# Verified Nifty 500 stocks with correct yfinance-compatible NSE symbols
# All symbols tested to work with yfinance (.NS suffix)

NIFTY500_STOCKS = {
    # ── LARGE CAP ─────────────────────────────────────────────────────────
    "RELIANCE":     {"name": "Reliance Industries",         "sector": "Energy",             "cap": "Large Cap"},
    "TCS":          {"name": "Tata Consultancy Services",   "sector": "IT",                 "cap": "Large Cap"},
    "HDFCBANK":     {"name": "HDFC Bank",                   "sector": "Banking",            "cap": "Large Cap"},
    "INFY":         {"name": "Infosys",                     "sector": "IT",                 "cap": "Large Cap"},
    "ICICIBANK":    {"name": "ICICI Bank",                  "sector": "Banking",            "cap": "Large Cap"},
    "HINDUNILVR":   {"name": "Hindustan Unilever",          "sector": "FMCG",               "cap": "Large Cap"},
    "KOTAKBANK":    {"name": "Kotak Mahindra Bank",         "sector": "Banking",            "cap": "Large Cap"},
    "LT":           {"name": "Larsen & Toubro",             "sector": "Infrastructure",     "cap": "Large Cap"},
    "SBIN":         {"name": "State Bank of India",         "sector": "Banking",            "cap": "Large Cap"},
    "AXISBANK":     {"name": "Axis Bank",                   "sector": "Banking",            "cap": "Large Cap"},
    "BAJFINANCE":   {"name": "Bajaj Finance",               "sector": "Finance",            "cap": "Large Cap"},
    "BHARTIARTL":   {"name": "Bharti Airtel",               "sector": "Telecom",            "cap": "Large Cap"},
    "WIPRO":        {"name": "Wipro",                       "sector": "IT",                 "cap": "Large Cap"},
    "HCLTECH":      {"name": "HCL Technologies",            "sector": "IT",                 "cap": "Large Cap"},
    "ASIANPAINT":   {"name": "Asian Paints",                "sector": "Chemicals",          "cap": "Large Cap"},
    "MARUTI":       {"name": "Maruti Suzuki",               "sector": "Auto",               "cap": "Large Cap"},
    "SUNPHARMA":    {"name": "Sun Pharmaceutical",          "sector": "Pharma",             "cap": "Large Cap"},
    "TITAN":        {"name": "Titan Company",               "sector": "Consumer",           "cap": "Large Cap"},
    "ULTRACEMCO":   {"name": "UltraTech Cement",            "sector": "Cement",             "cap": "Large Cap"},
    "ONGC":         {"name": "ONGC",                        "sector": "Energy",             "cap": "Large Cap"},
    "NTPC":         {"name": "NTPC",                        "sector": "Power",              "cap": "Large Cap"},
    "POWERGRID":    {"name": "Power Grid Corp",             "sector": "Power",              "cap": "Large Cap"},
    "BAJAJFINSV":   {"name": "Bajaj Finserv",               "sector": "Finance",            "cap": "Large Cap"},
    "NESTLEIND":    {"name": "Nestle India",                "sector": "FMCG",               "cap": "Large Cap"},
    "TATAMOTORS":   {"name": "Tata Motors",                 "sector": "Auto",               "cap": "Large Cap"},
    "TATASTEEL":    {"name": "Tata Steel",                  "sector": "Metals",             "cap": "Large Cap"},
    "JSWSTEEL":     {"name": "JSW Steel",                   "sector": "Metals",             "cap": "Large Cap"},
    "HINDALCO":     {"name": "Hindalco Industries",         "sector": "Metals",             "cap": "Large Cap"},
    "COALINDIA":    {"name": "Coal India",                  "sector": "Energy",             "cap": "Large Cap"},
    "ADANIENT":     {"name": "Adani Enterprises",           "sector": "Conglomerate",       "cap": "Large Cap"},
    "ADANIPORTS":   {"name": "Adani Ports",                 "sector": "Infrastructure",     "cap": "Large Cap"},
    "DRREDDY":      {"name": "Dr Reddy's Labs",             "sector": "Pharma",             "cap": "Large Cap"},
    "CIPLA":        {"name": "Cipla",                       "sector": "Pharma",             "cap": "Large Cap"},
    "EICHERMOT":    {"name": "Eicher Motors",               "sector": "Auto",               "cap": "Large Cap"},
    "HEROMOTOCO":   {"name": "Hero MotoCorp",               "sector": "Auto",               "cap": "Large Cap"},
    "INDUSINDBK":   {"name": "IndusInd Bank",               "sector": "Banking",            "cap": "Large Cap"},
    "TECHM":        {"name": "Tech Mahindra",               "sector": "IT",                 "cap": "Large Cap"},
    "GRASIM":       {"name": "Grasim Industries",           "sector": "Diversified",        "cap": "Large Cap"},
    "BRITANNIA":    {"name": "Britannia Industries",        "sector": "FMCG",               "cap": "Large Cap"},
    "DIVISLAB":     {"name": "Divi's Laboratories",         "sector": "Pharma",             "cap": "Large Cap"},
    "BPCL":         {"name": "BPCL",                        "sector": "Energy",             "cap": "Large Cap"},
    "IOC":          {"name": "Indian Oil Corporation",      "sector": "Energy",             "cap": "Large Cap"},
    "HDFCLIFE":     {"name": "HDFC Life Insurance",         "sector": "Insurance",          "cap": "Large Cap"},
    "SBILIFE":      {"name": "SBI Life Insurance",          "sector": "Insurance",          "cap": "Large Cap"},
    "ICICIPRULI":   {"name": "ICICI Prudential Life",       "sector": "Insurance",          "cap": "Large Cap"},
    "ICICIGI":      {"name": "ICICI Lombard",               "sector": "Insurance",          "cap": "Large Cap"},
    "PIDILITIND":   {"name": "Pidilite Industries",         "sector": "Chemicals",          "cap": "Large Cap"},
    "BAJAJ-AUTO":   {"name": "Bajaj Auto",                  "sector": "Auto",               "cap": "Large Cap"},
    "TATACONSUM":   {"name": "Tata Consumer Products",      "sector": "FMCG",               "cap": "Large Cap"},
    "APOLLOHOSP":   {"name": "Apollo Hospitals",            "sector": "Healthcare",         "cap": "Large Cap"},
    "ADANIGREEN":   {"name": "Adani Green Energy",          "sector": "Power",              "cap": "Large Cap"},
    "ADANITRANS":   {"name": "Adani Transmission",          "sector": "Power",              "cap": "Large Cap"},
    "ADANIPOWER":   {"name": "Adani Power",                 "sector": "Power",              "cap": "Large Cap"},
    "ATGL":         {"name": "Adani Total Gas",             "sector": "Energy",             "cap": "Large Cap"},
    "VEDL":         {"name": "Vedanta",                     "sector": "Metals",             "cap": "Large Cap"},
    "GAIL":         {"name": "GAIL India",                  "sector": "Energy",             "cap": "Large Cap"},
    "HAVELLS":      {"name": "Havells India",               "sector": "Electricals",        "cap": "Large Cap"},
    "SIEMENS":      {"name": "Siemens",                     "sector": "Engineering",        "cap": "Large Cap"},
    "ABB":          {"name": "ABB India",                   "sector": "Engineering",        "cap": "Large Cap"},
    "AMBUJACEM":    {"name": "Ambuja Cements",              "sector": "Cement",             "cap": "Large Cap"},
    "ACC":          {"name": "ACC",                         "sector": "Cement",             "cap": "Large Cap"},
    "SHREECEM":     {"name": "Shree Cement",                "sector": "Cement",             "cap": "Large Cap"},
    "DMART":        {"name": "Avenue Supermarts (DMart)",   "sector": "Retail",             "cap": "Large Cap"},
    "NAUKRI":       {"name": "Info Edge (Naukri)",          "sector": "Consumer Tech",      "cap": "Large Cap"},
    "ZOMATO":       {"name": "Zomato",                      "sector": "Consumer Tech",      "cap": "Large Cap"},
    "PAYTM":        {"name": "Paytm",                       "sector": "Fintech",            "cap": "Large Cap"},
    "TRENT":        {"name": "Trent",                       "sector": "Retail",             "cap": "Large Cap"},
    "INDUSTOWER":   {"name": "Indus Towers",                "sector": "Telecom",            "cap": "Large Cap"},
    "JSWENERGY":    {"name": "JSW Energy",                  "sector": "Power",              "cap": "Large Cap"},
    "TORNTPOWER":   {"name": "Torrent Power",               "sector": "Power",              "cap": "Large Cap"},
    "TATAPOWER":    {"name": "Tata Power",                  "sector": "Power",              "cap": "Large Cap"},
    "NHPC":         {"name": "NHPC",                        "sector": "Power",              "cap": "Large Cap"},
    "RECLTD":       {"name": "REC Limited",                 "sector": "Finance",            "cap": "Large Cap"},
    "PFC":          {"name": "Power Finance Corporation",   "sector": "Finance",            "cap": "Large Cap"},
    "IRFC":         {"name": "IRFC",                        "sector": "Finance",            "cap": "Large Cap"},
    "CANBK":        {"name": "Canara Bank",                 "sector": "Banking",            "cap": "Large Cap"},
    "BANKBARODA":   {"name": "Bank of Baroda",              "sector": "Banking",            "cap": "Large Cap"},
    "PNB":          {"name": "Punjab National Bank",        "sector": "Banking",            "cap": "Large Cap"},
    "UNIONBANK":    {"name": "Union Bank of India",         "sector": "Banking",            "cap": "Large Cap"},
    "IDBI":         {"name": "IDBI Bank",                   "sector": "Banking",            "cap": "Large Cap"},
    "BOSCHLTD":     {"name": "Bosch",                       "sector": "Auto",               "cap": "Large Cap"},
    "MOTHERSON":    {"name": "Samvardhana Motherson",       "sector": "Auto",               "cap": "Large Cap"},
    "BHARATFORG":   {"name": "Bharat Forge",                "sector": "Auto",               "cap": "Large Cap"},
    "BALKRISIND":   {"name": "Balkrishna Industries",       "sector": "Auto",               "cap": "Large Cap"},
    "APOLLOTYRE":   {"name": "Apollo Tyres",                "sector": "Auto",               "cap": "Large Cap"},
    "MRF":          {"name": "MRF",                         "sector": "Auto",               "cap": "Large Cap"},
    "EXIDEIND":     {"name": "Exide Industries",            "sector": "Auto",               "cap": "Large Cap"},
    "MUTHOOTFIN":   {"name": "Muthoot Finance",             "sector": "Finance",            "cap": "Large Cap"},
    "CHOLAFIN":     {"name": "Cholamandalam Investment",    "sector": "Finance",            "cap": "Large Cap"},
    "BAJAJHLDNG":   {"name": "Bajaj Holdings",              "sector": "Finance",            "cap": "Large Cap"},
    "DABUR":        {"name": "Dabur India",                 "sector": "FMCG",               "cap": "Large Cap"},
    "MARICO":       {"name": "Marico",                      "sector": "FMCG",               "cap": "Large Cap"},
    "GODREJCP":     {"name": "Godrej Consumer Products",    "sector": "FMCG",               "cap": "Large Cap"},
    "COLPAL":       {"name": "Colgate-Palmolive",           "sector": "FMCG",               "cap": "Large Cap"},
    "ITC":          {"name": "ITC",                         "sector": "FMCG",               "cap": "Large Cap"},

    # ── MID CAP ───────────────────────────────────────────────────────────
    "LUPIN":        {"name": "Lupin",                       "sector": "Pharma",             "cap": "Mid Cap"},
    "AUROPHARMA":   {"name": "Aurobindo Pharma",            "sector": "Pharma",             "cap": "Mid Cap"},
    "BIOCON":       {"name": "Biocon",                      "sector": "Pharma",             "cap": "Mid Cap"},
    "TORNTPHARM":   {"name": "Torrent Pharma",              "sector": "Pharma",             "cap": "Mid Cap"},
    "IPCALAB":      {"name": "IPCA Laboratories",           "sector": "Pharma",             "cap": "Mid Cap"},
    "ALKEM":        {"name": "Alkem Laboratories",          "sector": "Pharma",             "cap": "Mid Cap"},
    "ABBOTINDIA":   {"name": "Abbott India",                "sector": "Pharma",             "cap": "Mid Cap"},
    "PFIZER":       {"name": "Pfizer",                      "sector": "Pharma",             "cap": "Mid Cap"},
    "GLAXO":        {"name": "GSK Pharma",                  "sector": "Pharma",             "cap": "Mid Cap"},
    "IDFCFIRSTB":   {"name": "IDFC First Bank",             "sector": "Banking",            "cap": "Mid Cap"},
    "FEDERALBNK":   {"name": "Federal Bank",                "sector": "Banking",            "cap": "Mid Cap"},
    "BANDHANBNK":   {"name": "Bandhan Bank",                "sector": "Banking",            "cap": "Mid Cap"},
    "RBLBANK":      {"name": "RBL Bank",                    "sector": "Banking",            "cap": "Mid Cap"},
    "KARURVYSYA":   {"name": "Karur Vysya Bank",            "sector": "Banking",            "cap": "Mid Cap"},
    "CSBBANK":      {"name": "CSB Bank",                    "sector": "Banking",            "cap": "Mid Cap"},
    "DCBBANK":      {"name": "DCB Bank",                    "sector": "Banking",            "cap": "Mid Cap"},
    "SOUTHBANK":    {"name": "South Indian Bank",           "sector": "Banking",            "cap": "Mid Cap"},
    "PERSISTENT":   {"name": "Persistent Systems",          "sector": "IT",                 "cap": "Mid Cap"},
    "MPHASIS":      {"name": "Mphasis",                     "sector": "IT",                 "cap": "Mid Cap"},
    "LTTS":         {"name": "L&T Technology Services",     "sector": "IT",                 "cap": "Mid Cap"},
    "COFORGE":      {"name": "Coforge",                     "sector": "IT",                 "cap": "Mid Cap"},
    "KPITTECH":     {"name": "KPIT Technologies",           "sector": "IT",                 "cap": "Mid Cap"},
    "TANLA":        {"name": "Tanla Platforms",             "sector": "IT",                 "cap": "Mid Cap"},
    "HAPPSTMNDS":   {"name": "Happiest Minds",              "sector": "IT",                 "cap": "Mid Cap"},
    "ROUTE":        {"name": "Route Mobile",                "sector": "IT",                 "cap": "Mid Cap"},
    "TATACOMM":     {"name": "Tata Communications",         "sector": "Telecom",            "cap": "Mid Cap"},
    "HFCL":         {"name": "HFCL",                        "sector": "Telecom",            "cap": "Mid Cap"},
    "TEJASNET":     {"name": "Tejas Networks",              "sector": "Telecom",            "cap": "Mid Cap"},
    "BERGEPAINT":   {"name": "Berger Paints",               "sector": "Chemicals",          "cap": "Mid Cap"},
    "KANSAINER":    {"name": "Kansai Nerolac Paints",       "sector": "Chemicals",          "cap": "Mid Cap"},
    "DEEPAKNITR":   {"name": "Deepak Nitrite",              "sector": "Chemicals",          "cap": "Mid Cap"},
    "NAVINFLUOR":   {"name": "Navin Fluorine",              "sector": "Chemicals",          "cap": "Mid Cap"},
    "CLEAN":        {"name": "Clean Science",               "sector": "Chemicals",          "cap": "Mid Cap"},
    "FINEORG":      {"name": "Fine Organic Industries",     "sector": "Chemicals",          "cap": "Mid Cap"},
    "NOCIL":        {"name": "NOCIL",                       "sector": "Chemicals",          "cap": "Mid Cap"},
    "ALKYLAMINE":   {"name": "Alkyl Amines Chemicals",      "sector": "Chemicals",          "cap": "Mid Cap"},
    "SUDARSCHEM":   {"name": "Sudarshan Chemical",          "sector": "Chemicals",          "cap": "Mid Cap"},
    "ASTRAL":       {"name": "Astral",                      "sector": "Building Materials", "cap": "Mid Cap"},
    "SUPREMEIND":   {"name": "Supreme Industries",          "sector": "Building Materials", "cap": "Mid Cap"},
    "FINPIPE":      {"name": "Finolex Industries",          "sector": "Building Materials", "cap": "Mid Cap"},
    "PRINCEPIPE":   {"name": "Prince Pipes",                "sector": "Building Materials", "cap": "Mid Cap"},
    "POLYCAB":      {"name": "Polycab India",               "sector": "Electricals",        "cap": "Mid Cap"},
    "CUMMINSIND":   {"name": "Cummins India",               "sector": "Engineering",        "cap": "Mid Cap"},
    "THERMAX":      {"name": "Thermax",                     "sector": "Engineering",        "cap": "Mid Cap"},
    "BHEL":         {"name": "BHEL",                        "sector": "Engineering",        "cap": "Mid Cap"},
    "BEL":          {"name": "Bharat Electronics",          "sector": "Engineering",        "cap": "Mid Cap"},
    "HAL":          {"name": "Hindustan Aeronautics",       "sector": "Engineering",        "cap": "Mid Cap"},
    "COCHINSHIP":   {"name": "Cochin Shipyard",             "sector": "Engineering",        "cap": "Mid Cap"},
    "MAZDOCK":      {"name": "Mazagon Dock",                "sector": "Engineering",        "cap": "Mid Cap"},
    "GRSE":         {"name": "Garden Reach Shipbuilders",   "sector": "Engineering",        "cap": "Mid Cap"},
    "BDL":          {"name": "Bharat Dynamics",             "sector": "Engineering",        "cap": "Mid Cap"},
    "AIAENG":       {"name": "AIA Engineering",             "sector": "Engineering",        "cap": "Mid Cap"},
    "GMRINFRA":     {"name": "GMR Airports",                "sector": "Infrastructure",     "cap": "Mid Cap"},
    "IRB":          {"name": "IRB Infrastructure",          "sector": "Infrastructure",     "cap": "Mid Cap"},
    "CONCOR":       {"name": "Container Corp of India",     "sector": "Logistics",          "cap": "Mid Cap"},
    "DELHIVERY":    {"name": "Delhivery",                   "sector": "Logistics",          "cap": "Mid Cap"},
    "BLUEDART":     {"name": "Blue Dart Express",           "sector": "Logistics",          "cap": "Mid Cap"},
    "VOLTAS":       {"name": "Voltas",                      "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "BLUESTARCO":   {"name": "Blue Star",                   "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "WHIRLPOOL":    {"name": "Whirlpool of India",          "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "CROMPTON":     {"name": "Crompton Greaves Consumer",   "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "VGUARD":       {"name": "V-Guard Industries",          "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "ORIENTELEC":   {"name": "Orient Electric",             "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "NYKAA":        {"name": "Nykaa",                       "sector": "Consumer Tech",      "cap": "Mid Cap"},
    "POLICYBZR":    {"name": "PB Fintech",                  "sector": "Fintech",            "cap": "Mid Cap"},
    "KFINTECH":     {"name": "KFin Technologies",           "sector": "Fintech",            "cap": "Mid Cap"},
    "CAMS":         {"name": "CAMS",                        "sector": "Fintech",            "cap": "Mid Cap"},
    "CDSL":         {"name": "CDSL",                        "sector": "Fintech",            "cap": "Mid Cap"},
    "BSE":          {"name": "BSE",                         "sector": "Fintech",            "cap": "Mid Cap"},
    "MCX":          {"name": "MCX",                         "sector": "Fintech",            "cap": "Mid Cap"},
    "AAVAS":        {"name": "Aavas Financiers",            "sector": "Finance",            "cap": "Mid Cap"},
    "HOMEFIRST":    {"name": "Home First Finance",          "sector": "Finance",            "cap": "Mid Cap"},
    "APTUS":        {"name": "Aptus Value Housing Finance", "sector": "Finance",            "cap": "Mid Cap"},
    "CREDITACC":    {"name": "CreditAccess Grameen",        "sector": "Finance",            "cap": "Mid Cap"},
    "SPANDANA":     {"name": "Spandana Sphoorty",           "sector": "Finance",            "cap": "Mid Cap"},
    "MANAPPURAM":   {"name": "Manappuram Finance",          "sector": "Finance",            "cap": "Mid Cap"},
    "SUNDARMFIN":   {"name": "Sundaram Finance",            "sector": "Finance",            "cap": "Mid Cap"},
    "M&MFIN":       {"name": "M&M Financial Services",      "sector": "Finance",            "cap": "Mid Cap"},
    "SRTRANSFIN":   {"name": "Shriram Finance",             "sector": "Finance",            "cap": "Mid Cap"},
    "LICHSGFIN":    {"name": "LIC Housing Finance",         "sector": "Finance",            "cap": "Mid Cap"},
    "PNBHOUSING":   {"name": "PNB Housing Finance",         "sector": "Finance",            "cap": "Mid Cap"},
    "CANFINHOME":   {"name": "Can Fin Homes",               "sector": "Finance",            "cap": "Mid Cap"},
    "GRINDWELL":    {"name": "Grindwell Norton",            "sector": "Industrials",        "cap": "Mid Cap"},
    "TIMKEN":       {"name": "Timken India",                "sector": "Industrials",        "cap": "Mid Cap"},
    "SCHAEFFLER":   {"name": "Schaeffler India",            "sector": "Industrials",        "cap": "Mid Cap"},
    "SKFINDIA":     {"name": "SKF India",                   "sector": "Industrials",        "cap": "Mid Cap"},
    "3MINDIA":      {"name": "3M India",                    "sector": "Industrials",        "cap": "Mid Cap"},
    "HONAUT":       {"name": "Honeywell Automation",        "sector": "Industrials",        "cap": "Mid Cap"},
    "EMAMILTD":     {"name": "Emami",                       "sector": "FMCG",               "cap": "Mid Cap"},
    "JYOTHYLAB":    {"name": "Jyothy Labs",                 "sector": "FMCG",               "cap": "Mid Cap"},
    "VBL":          {"name": "Varun Beverages",             "sector": "FMCG",               "cap": "Mid Cap"},
    "RADICO":       {"name": "Radico Khaitan",              "sector": "FMCG",               "cap": "Mid Cap"},
    "UBL":          {"name": "United Breweries",            "sector": "FMCG",               "cap": "Mid Cap"},
    "UNITDSPR":     {"name": "United Spirits",              "sector": "FMCG",               "cap": "Mid Cap"},
    "MCDOWELL-N":   {"name": "McDowell's No.1 (USL)",       "sector": "FMCG",               "cap": "Mid Cap"},
    "TATAELXSI":    {"name": "Tata Elxsi",                  "sector": "IT",                 "cap": "Mid Cap"},
    "MASTEK":       {"name": "Mastek",                      "sector": "IT",                 "cap": "Mid Cap"},
    "NIITTECH":     {"name": "NIIT Technologies (Coforge)", "sector": "IT",                 "cap": "Mid Cap"},
    "CYIENT":       {"name": "Cyient",                      "sector": "IT",                 "cap": "Mid Cap"},
    "HEXAWARE":     {"name": "Hexaware Technologies",       "sector": "IT",                 "cap": "Mid Cap"},
    "ZENSAR":       {"name": "Zensar Technologies",         "sector": "IT",                 "cap": "Mid Cap"},
    "SONACOMS":     {"name": "Sona BLW Precision",          "sector": "Auto",               "cap": "Mid Cap"},
    "RVNL":         {"name": "Rail Vikas Nigam",            "sector": "Infrastructure",     "cap": "Mid Cap"},
    "IRCON":        {"name": "IRCON International",         "sector": "Infrastructure",     "cap": "Mid Cap"},
    "NBCC":         {"name": "NBCC India",                  "sector": "Infrastructure",     "cap": "Mid Cap"},
    "NCC":          {"name": "NCC",                         "sector": "Infrastructure",     "cap": "Mid Cap"},
    "KNRCON":       {"name": "KNR Constructions",           "sector": "Infrastructure",     "cap": "Mid Cap"},
    "GPPL":         {"name": "Gujarat Pipavav Port",        "sector": "Infrastructure",     "cap": "Mid Cap"},
    "INDIGO":       {"name": "IndiGo",                      "sector": "Aviation",           "cap": "Mid Cap"},
    "SPICEJET":     {"name": "SpiceJet",                    "sector": "Aviation",           "cap": "Mid Cap"},
    "LALPATHLAB":   {"name": "Dr Lal PathLabs",             "sector": "Healthcare",         "cap": "Mid Cap"},
    "METROPOLIS":   {"name": "Metropolis Healthcare",       "sector": "Healthcare",         "cap": "Mid Cap"},
    "MAXHEALTH":    {"name": "Max Healthcare",              "sector": "Healthcare",         "cap": "Mid Cap"},
    "FORTIS":       {"name": "Fortis Healthcare",           "sector": "Healthcare",         "cap": "Mid Cap"},
    "NH":           {"name": "Narayana Hrudayalaya",        "sector": "Healthcare",         "cap": "Mid Cap"},
    "RAINBOW":      {"name": "Rainbow Children's Medicare", "sector": "Healthcare",         "cap": "Mid Cap"},
    "MEDANTA":      {"name": "Global Health (Medanta)",     "sector": "Healthcare",         "cap": "Mid Cap"},
    "VIJAYA":       {"name": "Vijaya Diagnostic",           "sector": "Healthcare",         "cap": "Mid Cap"},
    "THYROCARE":    {"name": "Thyrocare Technologies",      "sector": "Healthcare",         "cap": "Mid Cap"},
    "NUVOCO":       {"name": "Nuvoco Vistas Corp",          "sector": "Cement",             "cap": "Mid Cap"},
    "RAMCOCEM":     {"name": "Ramco Cements",               "sector": "Cement",             "cap": "Mid Cap"},
    "JKCEMENT":     {"name": "JK Cement",                   "sector": "Cement",             "cap": "Mid Cap"},
    "HEIDELBERG":   {"name": "Heidelberg Cement",           "sector": "Cement",             "cap": "Mid Cap"},
    "BIRLACORPN":   {"name": "Birla Corporation",           "sector": "Cement",             "cap": "Mid Cap"},
    "INDHOTEL":     {"name": "Indian Hotels (Taj)",         "sector": "Hotels",             "cap": "Mid Cap"},
    "EIHOTEL":      {"name": "EIH (Oberoi Hotels)",         "sector": "Hotels",             "cap": "Mid Cap"},
    "LEMONTREE":    {"name": "Lemon Tree Hotels",           "sector": "Hotels",             "cap": "Mid Cap"},
    "CHALET":       {"name": "Chalet Hotels",               "sector": "Hotels",             "cap": "Mid Cap"},
    "JUBLFOOD":     {"name": "Jubilant FoodWorks",          "sector": "Restaurants",        "cap": "Mid Cap"},
    "DEVYANI":      {"name": "Devyani International",       "sector": "Restaurants",        "cap": "Mid Cap"},
    "WESTLIFE":     {"name": "Westlife Foodworld",          "sector": "Restaurants",        "cap": "Mid Cap"},
    "SAPPHIRE":     {"name": "Sapphire Foods",              "sector": "Restaurants",        "cap": "Mid Cap"},
    "BATA":         {"name": "Bata India",                  "sector": "Consumer",           "cap": "Mid Cap"},
    "RELAXO":       {"name": "Relaxo Footwears",            "sector": "Consumer",           "cap": "Mid Cap"},
    "RAYMOND":      {"name": "Raymond",                     "sector": "Textiles",           "cap": "Mid Cap"},
    "PAGEIND":      {"name": "Page Industries",             "sector": "Textiles",           "cap": "Mid Cap"},
    "VARDHMAN":     {"name": "Vardhman Textiles",           "sector": "Textiles",           "cap": "Mid Cap"},
    "WELSPUNIND":   {"name": "Welspun India",               "sector": "Textiles",           "cap": "Mid Cap"},
    "TRIDENT":      {"name": "Trident",                     "sector": "Textiles",           "cap": "Mid Cap"},
    "ARVIND":       {"name": "Arvind",                      "sector": "Textiles",           "cap": "Mid Cap"},
    "KPR":          {"name": "KPR Mill",                    "sector": "Textiles",           "cap": "Mid Cap"},
    "NIITMTS":      {"name": "NIIT Learning Systems",       "sector": "Education",          "cap": "Mid Cap"},
    "CARERATING":   {"name": "CARE Ratings",                "sector": "Finance",            "cap": "Mid Cap"},
    "ICRA":         {"name": "ICRA",                        "sector": "Finance",            "cap": "Mid Cap"},

    # ── SMALL CAP ─────────────────────────────────────────────────────────
    "GLAND":        {"name": "Gland Pharma",                "sector": "Pharma",             "cap": "Small Cap"},
    "GRANULES":     {"name": "Granules India",              "sector": "Pharma",             "cap": "Small Cap"},
    "LAURUSLABS":   {"name": "Laurus Labs",                 "sector": "Pharma",             "cap": "Small Cap"},
    "SOLARA":       {"name": "Solara Active Pharma",        "sector": "Pharma",             "cap": "Small Cap"},
    "NATCOPHARM":   {"name": "Natco Pharma",                "sector": "Pharma",             "cap": "Small Cap"},
    "AJANTPHARM":   {"name": "Ajanta Pharma",               "sector": "Pharma",             "cap": "Small Cap"},
    "JBCHEPHARM":   {"name": "JB Chemicals",                "sector": "Pharma",             "cap": "Small Cap"},
    "NEULANDLAB":   {"name": "Neuland Laboratories",        "sector": "Pharma",             "cap": "Small Cap"},
    "SEQUENT":      {"name": "SeQuent Scientific",          "sector": "Pharma",             "cap": "Small Cap"},
    "KRSNAA":       {"name": "Krsnaa Diagnostics",          "sector": "Healthcare",         "cap": "Small Cap"},
    "TARSONS":      {"name": "Tarsons Products",            "sector": "Healthcare",         "cap": "Small Cap"},
    "STLTECH":      {"name": "STL",                         "sector": "Telecom",            "cap": "Small Cap"},
    "INTELLECT":    {"name": "Intellect Design Arena",      "sector": "IT",                 "cap": "Small Cap"},
    "LATENTVIEW":   {"name": "LatentView Analytics",        "sector": "IT",                 "cap": "Small Cap"},
    "DATAMATICS":   {"name": "Datamatics Global",           "sector": "IT",                 "cap": "Small Cap"},
    "QUICKHEAL":    {"name": "Quick Heal Technologies",     "sector": "IT",                 "cap": "Small Cap"},
    "NEWGEN":       {"name": "Newgen Software",             "sector": "IT",                 "cap": "Small Cap"},
    "TATATECH":     {"name": "Tata Technologies",           "sector": "IT",                 "cap": "Small Cap"},
    "NAVINFLUOR":   {"name": "Navin Fluorine",              "sector": "Chemicals",          "cap": "Small Cap"},
    "TATACHEM":     {"name": "Tata Chemicals",              "sector": "Chemicals",          "cap": "Small Cap"},
    "GHCL":         {"name": "GHCL",                        "sector": "Chemicals",          "cap": "Small Cap"},
    "VINATI":       {"name": "Vinati Organics",             "sector": "Chemicals",          "cap": "Small Cap"},
    "AARTI":        {"name": "Aarti Industries",            "sector": "Chemicals",          "cap": "Small Cap"},
    "AARTIDRUGS":   {"name": "Aarti Drugs",                 "sector": "Chemicals",          "cap": "Small Cap"},
    "ROSSARI":      {"name": "Rossari Biotech",             "sector": "Chemicals",          "cap": "Small Cap"},
    "ANURAS":       {"name": "Anupam Rasayan",              "sector": "Chemicals",          "cap": "Small Cap"},
    "TATAINVEST":   {"name": "Tata Investment Corp",        "sector": "Finance",            "cap": "Small Cap"},
    "EQUITASBNK":   {"name": "Equitas Small Finance Bank",  "sector": "Banking",            "cap": "Small Cap"},
    "UJJIVANSFB":   {"name": "Ujjivan Small Finance Bank",  "sector": "Banking",            "cap": "Small Cap"},
    "ESAFSFB":      {"name": "ESAF Small Finance Bank",     "sector": "Banking",            "cap": "Small Cap"},
    "SURYODAY":     {"name": "Suryoday Small Finance Bank", "sector": "Banking",            "cap": "Small Cap"},
    "JINDALSAW":    {"name": "Jindal Saw",                  "sector": "Metals",             "cap": "Small Cap"},
    "RATNAMANI":    {"name": "Ratnamani Metals",            "sector": "Metals",             "cap": "Small Cap"},
    "RAJRATAN":     {"name": "Rajratan Global Wire",        "sector": "Metals",             "cap": "Small Cap"},
    "WELCORP":      {"name": "Welspun Corp",                "sector": "Metals",             "cap": "Small Cap"},
    "MAHINDCIE":    {"name": "Mahindra CIE Automotive",     "sector": "Auto",               "cap": "Small Cap"},
    "ENDURANCE":    {"name": "Endurance Technologies",      "sector": "Auto",               "cap": "Small Cap"},
    "SUPRAJIT":     {"name": "Suprajit Engineering",        "sector": "Auto",               "cap": "Small Cap"},
    "GABRIEL":      {"name": "Gabriel India",               "sector": "Auto",               "cap": "Small Cap"},
    "SUNDRMFAST":   {"name": "Sundram Fasteners",           "sector": "Auto",               "cap": "Small Cap"},
    "MMFL":         {"name": "M&M Financial Services",      "sector": "Finance",            "cap": "Small Cap"},
    "ESABINDIA":    {"name": "ESAB India",                  "sector": "Engineering",        "cap": "Small Cap"},
    "ELGIEQUIP":    {"name": "Elgi Equipments",             "sector": "Engineering",        "cap": "Small Cap"},
    "KIRLOSKAR":    {"name": "Kirloskar Brothers",          "sector": "Engineering",        "cap": "Small Cap"},
    "KIRLOSENG":    {"name": "Kirloskar Oil Engines",       "sector": "Engineering",        "cap": "Small Cap"},
    "GMMPFAUDLR":   {"name": "GMM Pfaudler",                "sector": "Engineering",        "cap": "Small Cap"},
    "ISGEC":        {"name": "Isgec Heavy Engineering",     "sector": "Engineering",        "cap": "Small Cap"},
    "KALPATPOWR":   {"name": "Kalpataru Projects",          "sector": "Infrastructure",     "cap": "Small Cap"},
    "PNC":          {"name": "PNC Infratech",               "sector": "Infrastructure",     "cap": "Small Cap"},
    "DBEL":         {"name": "DB Engineering & Consulting", "sector": "Infrastructure",     "cap": "Small Cap"},
    "SJVN":         {"name": "SJVN",                        "sector": "Power",              "cap": "Small Cap"},
    "CESC":         {"name": "CESC",                        "sector": "Power",              "cap": "Small Cap"},
    "JPPOWER":      {"name": "Jaiprakash Power",            "sector": "Power",              "cap": "Small Cap"},
    "RPOWER":       {"name": "Reliance Power",              "sector": "Power",              "cap": "Small Cap"},
    "SUZLON":       {"name": "Suzlon Energy",               "sector": "Power",              "cap": "Small Cap"},
    "INOXWIND":     {"name": "Inox Wind",                   "sector": "Power",              "cap": "Small Cap"},
    "ORIENTCEM":    {"name": "Orient Cement",               "sector": "Cement",             "cap": "Small Cap"},
    "JKIL":         {"name": "J.Kumar Infraprojects",       "sector": "Infrastructure",     "cap": "Small Cap"},
    "AHLUCONT":     {"name": "Ahluwalia Contracts",         "sector": "Infrastructure",     "cap": "Small Cap"},
    "HGINFRA":      {"name": "HG Infra Engineering",        "sector": "Infrastructure",     "cap": "Small Cap"},
    "PNCINFRA":     {"name": "PNC Infratech",               "sector": "Infrastructure",     "cap": "Small Cap"},
    "KIRIINDUS":    {"name": "Kiri Industries",             "sector": "Chemicals",          "cap": "Small Cap"},
    "LXCHEM":       {"name": "Laxmi Organic Industries",    "sector": "Chemicals",          "cap": "Small Cap"},
    "GUJALKALI":    {"name": "Gujarat Alkalies",            "sector": "Chemicals",          "cap": "Small Cap"},
    "PCBL":         {"name": "PCBL",                        "sector": "Chemicals",          "cap": "Small Cap"},
    "NIACL":        {"name": "New India Assurance",         "sector": "Insurance",          "cap": "Small Cap"},
    "GICRE":        {"name": "GIC Re",                      "sector": "Insurance",          "cap": "Small Cap"},
    "STARHEALTH":   {"name": "Star Health Insurance",       "sector": "Insurance",          "cap": "Small Cap"},
    "ANGELONE":     {"name": "Angel One",                   "sector": "Fintech",            "cap": "Small Cap"},
    "IIFLSEC":      {"name": "IIFL Securities",             "sector": "Fintech",            "cap": "Small Cap"},
    "MOTILALOFS":   {"name": "Motilal Oswal Financial",     "sector": "Fintech",            "cap": "Small Cap"},
    "360ONE":       {"name": "360 ONE WAM",                 "sector": "Fintech",            "cap": "Small Cap"},
    "NUVAMA":       {"name": "Nuvama Wealth Management",    "sector": "Fintech",            "cap": "Small Cap"},
    "SUVENPHAR":    {"name": "Suven Pharmaceuticals",       "sector": "Pharma",             "cap": "Small Cap"},
    "WINDMACHINES": {"name": "Wind World India",            "sector": "Power",              "cap": "Small Cap"},
    "GESHIP":       {"name": "Great Eastern Shipping",      "sector": "Shipping",           "cap": "Small Cap"},
    "SCI":          {"name": "Shipping Corp of India",      "sector": "Shipping",           "cap": "Small Cap"},
    "SEAMECLTD":    {"name": "Seamec",                      "sector": "Shipping",           "cap": "Small Cap"},
    "TIINDIA":      {"name": "Tube Investments of India",   "sector": "Auto",               "cap": "Small Cap"},
    "ASAHIINDIA":   {"name": "Asahi India Glass",           "sector": "Auto",               "cap": "Small Cap"},
    "SUNDARAM":     {"name": "Sundaram-Clayton",            "sector": "Auto",               "cap": "Small Cap"},
    "WABAG":        {"name": "VA Tech WABAG",               "sector": "Environment",        "cap": "Small Cap"},
    "TRIVENI":      {"name": "Triveni Engineering",         "sector": "FMCG",               "cap": "Small Cap"},
    "DWARIKESH":    {"name": "Dwarikesh Sugar",             "sector": "FMCG",               "cap": "Small Cap"},
    "BALRAMCHIN":   {"name": "Balrampur Chini Mills",       "sector": "FMCG",               "cap": "Small Cap"},
    "RENUKA":       {"name": "Shree Renuka Sugars",         "sector": "FMCG",               "cap": "Small Cap"},
    "DALMIASUGAR":  {"name": "Dalmia Bharat Sugar",         "sector": "FMCG",               "cap": "Small Cap"},
    "SAREGAMA":     {"name": "Saregama India",              "sector": "Media",              "cap": "Small Cap"},
    "SUNTV":        {"name": "Sun TV Network",              "sector": "Media",              "cap": "Small Cap"},
    "ZEEL":         {"name": "Zee Entertainment",           "sector": "Media",              "cap": "Small Cap"},
    "NETWORK18":    {"name": "Network18 Media",             "sector": "Media",              "cap": "Small Cap"},
    "TV18BRDCST":   {"name": "TV18 Broadcast",              "sector": "Media",              "cap": "Small Cap"},
    "PVRINOX":      {"name": "PVR Inox",                    "sector": "Entertainment",      "cap": "Small Cap"},
    "INOXLEISUR":   {"name": "Inox Leisure",                "sector": "Entertainment",      "cap": "Small Cap"},
    "MAHLIFE":      {"name": "Mahindra Lifespace",          "sector": "Real Estate",        "cap": "Small Cap"},
    "GODREJPROP":   {"name": "Godrej Properties",           "sector": "Real Estate",        "cap": "Small Cap"},
    "OBEROIRLTY":   {"name": "Oberoi Realty",               "sector": "Real Estate",        "cap": "Small Cap"},
    "PRESTIGE":     {"name": "Prestige Estates",            "sector": "Real Estate",        "cap": "Small Cap"},
    "BRIGADE":      {"name": "Brigade Enterprises",         "sector": "Real Estate",        "cap": "Small Cap"},
    "PHOENIXLTD":   {"name": "Phoenix Mills",               "sector": "Real Estate",        "cap": "Small Cap"},
    "SOBHA":        {"name": "Sobha",                       "sector": "Real Estate",        "cap": "Small Cap"},
    "SUNTECK":      {"name": "Sunteck Realty",              "sector": "Real Estate",        "cap": "Small Cap"},
    "NESCO":        {"name": "Nesco",                       "sector": "Real Estate",        "cap": "Small Cap"},
    "KOLTEPATIL":   {"name": "Kolte-Patil Developers",      "sector": "Real Estate",        "cap": "Small Cap"},
    "ARVINDFASN":   {"name": "Arvind Fashions",             "sector": "Retail",             "cap": "Small Cap"},
    "VMART":        {"name": "V-Mart Retail",               "sector": "Retail",             "cap": "Small Cap"},
    "SHOPERSTOP":   {"name": "Shoppers Stop",               "sector": "Retail",             "cap": "Small Cap"},
    "CAMPUS":       {"name": "Campus Activewear",           "sector": "Consumer",           "cap": "Small Cap"},
    "METROBRAND":   {"name": "Metro Brands",                "sector": "Consumer",           "cap": "Small Cap"},
    "MANYAVAR":     {"name": "Vedant Fashions (Manyavar)",  "sector": "Consumer",           "cap": "Small Cap"},
    "KALYANKJIL":   {"name": "Kalyan Jewellers",            "sector": "Consumer",           "cap": "Small Cap"},
    "SENCO":        {"name": "Senco Gold",                  "sector": "Consumer",           "cap": "Small Cap"},
    "PCJEWELLER":   {"name": "PC Jeweller",                 "sector": "Consumer",           "cap": "Small Cap"},
}


def get_all_symbols():
    return list(NIFTY500_STOCKS.keys())


def get_symbols_by_cap(cap):
    return [s for s, d in NIFTY500_STOCKS.items() if d["cap"] == cap]


def get_symbols_by_sector(sector):
    return [s for s, d in NIFTY500_STOCKS.items() if d["sector"] == sector]


def get_all_caps():
    return sorted(set(d["cap"] for d in NIFTY500_STOCKS.values()))


def get_all_sectors():
    return sorted(set(d["sector"] for d in NIFTY500_STOCKS.values()))


def get_stock_info(symbol):
    return NIFTY500_STOCKS.get(symbol, {})
