# Official Nifty 500 list - mapped to NSE trading symbols
# Source: NSE India ind_nifty500list.csv

NIFTY500_STOCKS = {
    "360ONE":       {"name": "360 ONE WAM Ltd.",                         "sector": "Finance",            "cap": "Mid Cap"},
    "3MINDIA":      {"name": "3M India Ltd.",                            "sector": "Industrials",        "cap": "Mid Cap"},
    "ABB":          {"name": "ABB India Ltd.",                           "sector": "Engineering",        "cap": "Large Cap"},
    "ACC":          {"name": "ACC Ltd.",                                  "sector": "Cement",             "cap": "Large Cap"},
    "ACMESOLAR":    {"name": "ACME Solar Holdings Ltd.",                 "sector": "Power",              "cap": "Mid Cap"},
    "AIAENG":       {"name": "AIA Engineering Ltd.",                     "sector": "Engineering",        "cap": "Mid Cap"},
    "APLAPOLLO":    {"name": "APL Apollo Tubes Ltd.",                    "sector": "Metals",             "cap": "Mid Cap"},
    "AUBANK":       {"name": "AU Small Finance Bank Ltd.",               "sector": "Banking",            "cap": "Mid Cap"},
    "AWL":          {"name": "AWL Agri Business Ltd.",                   "sector": "FMCG",               "cap": "Mid Cap"},
    "AADHARHFC":    {"name": "Aadhar Housing Finance Ltd.",              "sector": "Finance",            "cap": "Small Cap"},
    "AARTI":        {"name": "Aarti Industries Ltd.",                    "sector": "Chemicals",          "cap": "Mid Cap"},
    "AAVAS":        {"name": "Aavas Financiers Ltd.",                    "sector": "Finance",            "cap": "Mid Cap"},
    "ABBOTINDIA":   {"name": "Abbott India Ltd.",                        "sector": "Pharma",             "cap": "Mid Cap"},
    "ACE":          {"name": "Action Construction Equipment Ltd.",       "sector": "Engineering",        "cap": "Small Cap"},
    "ADANIENSOL":   {"name": "Adani Energy Solutions Ltd.",              "sector": "Power",              "cap": "Large Cap"},
    "ADANIENT":     {"name": "Adani Enterprises Ltd.",                   "sector": "Conglomerate",       "cap": "Large Cap"},
    "ADANIGREEN":   {"name": "Adani Green Energy Ltd.",                  "sector": "Power",              "cap": "Large Cap"},
    "ADANIPORTS":   {"name": "Adani Ports and Special Economic Zone Ltd.", "sector": "Infrastructure",    "cap": "Large Cap"},
    "ADANIPOWER":   {"name": "Adani Power Ltd.",                         "sector": "Power",              "cap": "Large Cap"},
    "ATGL":         {"name": "Adani Total Gas Ltd.",                     "sector": "Energy",             "cap": "Large Cap"},
    "ABCAPITAL":    {"name": "Aditya Birla Capital Ltd.",                "sector": "Finance",            "cap": "Large Cap"},
    "ABFRL":        {"name": "Aditya Birla Fashion and Retail Ltd.",     "sector": "Retail",             "cap": "Mid Cap"},
    "ABSLBSETF":    {"name": "Aditya Birla Lifestyle Brands Ltd.",       "sector": "Consumer",           "cap": "Mid Cap"},
    "ABREALESTATE": {"name": "Aditya Birla Real Estate Ltd.",            "sector": "Real Estate",        "cap": "Mid Cap"},
    "ABSLAMC":      {"name": "Aditya Birla Sun Life AMC Ltd.",           "sector": "Finance",            "cap": "Mid Cap"},
    "AEGISLOG":     {"name": "Aegis Logistics Ltd.",                     "sector": "Logistics",          "cap": "Mid Cap"},
    "AEGISVOPAK":   {"name": "Aegis Vopak Terminals Ltd.",               "sector": "Logistics",          "cap": "Mid Cap"},
    "AFCONS":       {"name": "Afcons Infrastructure Ltd.",               "sector": "Infrastructure",     "cap": "Mid Cap"},
    "AFFLE":        {"name": "Affle 3i Ltd.",                            "sector": "Consumer Tech",      "cap": "Mid Cap"},
    "AJANTPHARM":   {"name": "Ajanta Pharmaceuticals Ltd.",              "sector": "Pharma",             "cap": "Small Cap"},
    "AKUMS":        {"name": "Akums Drugs and Pharmaceuticals Ltd.",     "sector": "Pharma",             "cap": "Small Cap"},
    "AKZOINDIA":    {"name": "Akzo Nobel India Ltd.",                    "sector": "Chemicals",          "cap": "Small Cap"},
    "ALEMBICLTD":   {"name": "Alembic Pharmaceuticals Ltd.",             "sector": "Pharma",             "cap": "Small Cap"},
    "ALKEM":        {"name": "Alkem Laboratories Ltd.",                  "sector": "Pharma",             "cap": "Mid Cap"},
    "ALKYLAMINE":   {"name": "Alkyl Amines Chemicals Ltd.",              "sector": "Chemicals",          "cap": "Small Cap"},
    "ALOKINDS":     {"name": "Alok Industries Ltd.",                     "sector": "Textiles",           "cap": "Small Cap"},
    "AMARAJABAT":   {"name": "Amara Raja Energy & Mobility Ltd.",        "sector": "Auto",               "cap": "Mid Cap"},
    "AMBER":        {"name": "Amber Enterprises India Ltd.",             "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "AMBUJACEM":    {"name": "Ambuja Cements Ltd.",                      "sector": "Cement",             "cap": "Large Cap"},
    "ANANDRATHI":   {"name": "Anand Rathi Wealth Ltd.",                  "sector": "Finance",            "cap": "Small Cap"},
    "ANANTRAJ":     {"name": "Anant Raj Ltd.",                           "sector": "Real Estate",        "cap": "Small Cap"},
    "ANGELONE":     {"name": "Angel One Ltd.",                           "sector": "Fintech",            "cap": "Mid Cap"},
    "APARINDS":     {"name": "Apar Industries Ltd.",                     "sector": "Electricals",        "cap": "Mid Cap"},
    "APOLLOHOSP":   {"name": "Apollo Hospitals Enterprise Ltd.",         "sector": "Healthcare",         "cap": "Large Cap"},
    "APOLLOTYRE":   {"name": "Apollo Tyres Ltd.",                        "sector": "Auto",               "cap": "Large Cap"},
    "APTUS":        {"name": "Aptus Value Housing Finance India Ltd.",   "sector": "Finance",            "cap": "Small Cap"},
    "ASAHIINDIA":   {"name": "Asahi India Glass Ltd.",                   "sector": "Auto",               "cap": "Small Cap"},
    "ASHOKLEY":     {"name": "Ashok Leyland Ltd.",                       "sector": "Auto",               "cap": "Large Cap"},
    "ASIANPAINT":   {"name": "Asian Paints Ltd.",                        "sector": "Chemicals",          "cap": "Large Cap"},
    "ASTERDM":      {"name": "Aster DM Healthcare Ltd.",                 "sector": "Healthcare",         "cap": "Mid Cap"},
    "ASTRAZEN":     {"name": "AstraZenca Pharma India Ltd.",             "sector": "Pharma",             "cap": "Small Cap"},
    "ASTRAL":       {"name": "Astral Ltd.",                              "sector": "Building Materials", "cap": "Mid Cap"},
    "ATHER":        {"name": "Ather Energy Ltd.",                        "sector": "Auto",               "cap": "Mid Cap"},
    "ATUL":         {"name": "Atul Ltd.",                                "sector": "Chemicals",          "cap": "Mid Cap"},
    "AUROPHARMA":   {"name": "Aurobindo Pharma Ltd.",                    "sector": "Pharma",             "cap": "Large Cap"},
    "AUTHUM":       {"name": "Authum Investment & Infrastructure Ltd.",  "sector": "Finance",            "cap": "Small Cap"},
    "DMART":        {"name": "Avenue Supermarts Ltd.",                   "sector": "Retail",             "cap": "Large Cap"},
    "AXISBANK":     {"name": "Axis Bank Ltd.",                           "sector": "Banking",            "cap": "Large Cap"},
    "BASF":         {"name": "BASF India Ltd.",                          "sector": "Chemicals",          "cap": "Small Cap"},
    "BEML":         {"name": "BEML Ltd.",                                "sector": "Engineering",        "cap": "Mid Cap"},
    "BLS":          {"name": "BLS International Services Ltd.",          "sector": "Services",           "cap": "Small Cap"},
    "BSE":          {"name": "BSE Ltd.",                                 "sector": "Fintech",            "cap": "Mid Cap"},
    "BAJAJ-AUTO":   {"name": "Bajaj Auto Ltd.",                          "sector": "Auto",               "cap": "Large Cap"},
    "BAJFINANCE":   {"name": "Bajaj Finance Ltd.",                       "sector": "Finance",            "cap": "Large Cap"},
    "BAJAJFINSV":   {"name": "Bajaj Finserv Ltd.",                       "sector": "Finance",            "cap": "Large Cap"},
    "BAJAJHLDNG":   {"name": "Bajaj Holdings & Investment Ltd.",         "sector": "Finance",            "cap": "Large Cap"},
    "BAJAJHFL":     {"name": "Bajaj Housing Finance Ltd.",               "sector": "Finance",            "cap": "Large Cap"},
    "BALKRISIND":   {"name": "Balkrishna Industries Ltd.",               "sector": "Auto",               "cap": "Large Cap"},
    "BALRAMCHIN":   {"name": "Balrampur Chini Mills Ltd.",               "sector": "FMCG",               "cap": "Small Cap"},
    "BANDHANBNK":   {"name": "Bandhan Bank Ltd.",                        "sector": "Banking",            "cap": "Mid Cap"},
    "BANKBARODA":   {"name": "Bank of Baroda",                           "sector": "Banking",            "cap": "Large Cap"},
    "BANKINDIA":    {"name": "Bank of India",                            "sector": "Banking",            "cap": "Mid Cap"},
    "MAHABANK":     {"name": "Bank of Maharashtra",                      "sector": "Banking",            "cap": "Mid Cap"},
    "BATAINDIA":    {"name": "Bata India Ltd.",                          "sector": "Consumer",           "cap": "Mid Cap"},
    "BAYERCROP":    {"name": "Bayer Cropscience Ltd.",                   "sector": "Chemicals",          "cap": "Small Cap"},
    "BERGEPAINT":   {"name": "Berger Paints India Ltd.",                 "sector": "Chemicals",          "cap": "Large Cap"},
    "BDL":          {"name": "Bharat Dynamics Ltd.",                     "sector": "Engineering",        "cap": "Mid Cap"},
    "BEL":          {"name": "Bharat Electronics Ltd.",                  "sector": "Engineering",        "cap": "Large Cap"},
    "BHARATFORG":   {"name": "Bharat Forge Ltd.",                        "sector": "Auto",               "cap": "Large Cap"},
    "BHEL":         {"name": "Bharat Heavy Electricals Ltd.",            "sector": "Engineering",        "cap": "Large Cap"},
    "BPCL":         {"name": "Bharat Petroleum Corporation Ltd.",        "sector": "Energy",             "cap": "Large Cap"},
    "BHARTIARTL":   {"name": "Bharti Airtel Ltd.",                       "sector": "Telecom",            "cap": "Large Cap"},
    "BHARTIHEXA":   {"name": "Bharti Hexacom Ltd.",                      "sector": "Telecom",            "cap": "Mid Cap"},
    "BIKAJI":       {"name": "Bikaji Foods International Ltd.",          "sector": "FMCG",               "cap": "Small Cap"},
    "BIOCON":       {"name": "Biocon Ltd.",                              "sector": "Pharma",             "cap": "Large Cap"},
    "BSOFT":        {"name": "Birlasoft Ltd.",                           "sector": "IT",                 "cap": "Mid Cap"},
    "BLUEDART":     {"name": "Blue Dart Express Ltd.",                   "sector": "Logistics",          "cap": "Mid Cap"},
    "BLUEJET":      {"name": "Blue Jet Healthcare Ltd.",                 "sector": "Pharma",             "cap": "Small Cap"},
    "BLUESTARCO":   {"name": "Blue Star Ltd.",                           "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "BBTC":         {"name": "Bombay Burmah Trading Corporation Ltd.",   "sector": "Diversified",        "cap": "Small Cap"},
    "BOSCHLTD":     {"name": "Bosch Ltd.",                               "sector": "Auto",               "cap": "Large Cap"},
    "BRAINBEES":    {"name": "Brainbees Solutions Ltd.",                 "sector": "Retail",             "cap": "Mid Cap"},
    "BRIGADE":      {"name": "Brigade Enterprises Ltd.",                 "sector": "Real Estate",        "cap": "Mid Cap"},
    "BRITANNIA":    {"name": "Britannia Industries Ltd.",                "sector": "FMCG",               "cap": "Large Cap"},
    "MAPMYINDIA":   {"name": "C.E. Info Systems Ltd.",                   "sector": "IT",                 "cap": "Small Cap"},
    "CCLPROD":      {"name": "CCL Products (I) Ltd.",                    "sector": "FMCG",               "cap": "Small Cap"},
    "CESC":         {"name": "CESC Ltd.",                                "sector": "Power",              "cap": "Mid Cap"},
    "CGPOWER":      {"name": "CG Power and Industrial Solutions Ltd.",   "sector": "Engineering",        "cap": "Large Cap"},
    "CRISIL":       {"name": "CRISIL Ltd.",                              "sector": "Finance",            "cap": "Mid Cap"},
    "CAMPUS":       {"name": "Campus Activewear Ltd.",                   "sector": "Consumer",           "cap": "Small Cap"},
    "CANFINHOME":   {"name": "Can Fin Homes Ltd.",                       "sector": "Finance",            "cap": "Mid Cap"},
    "CANBK":        {"name": "Canara Bank",                              "sector": "Banking",            "cap": "Large Cap"},
    "CAPLIPOINT":   {"name": "Caplin Point Laboratories Ltd.",           "sector": "Pharma",             "cap": "Small Cap"},
    "CGCL":         {"name": "Capri Global Capital Ltd.",                "sector": "Finance",            "cap": "Small Cap"},
    "CARBORUNIV":   {"name": "Carborundum Universal Ltd.",               "sector": "Industrials",        "cap": "Small Cap"},
    "CASTROLIND":   {"name": "Castrol India Ltd.",                       "sector": "Energy",             "cap": "Mid Cap"},
    "CEATLTD":      {"name": "Ceat Ltd.",                                "sector": "Auto",               "cap": "Mid Cap"},
    "CENTRALBK":    {"name": "Central Bank of India",                    "sector": "Banking",            "cap": "Mid Cap"},
    "CDSL":         {"name": "Central Depository Services (India) Ltd.", "sector": "Fintech",            "cap": "Mid Cap"},
    "CENTURYPLY":   {"name": "Century Plyboards (India) Ltd.",           "sector": "Building Materials", "cap": "Mid Cap"},
    "CERA":         {"name": "Cera Sanitaryware Ltd",                    "sector": "Building Materials", "cap": "Small Cap"},
    "CHALET":       {"name": "Chalet Hotels Ltd.",                       "sector": "Hotels",             "cap": "Small Cap"},
    "CHAMBLFERT":   {"name": "Chambal Fertilizers & Chemicals Ltd.",     "sector": "Chemicals",          "cap": "Mid Cap"},
    "CHENNPETRO":   {"name": "Chennai Petroleum Corporation Ltd.",       "sector": "Energy",             "cap": "Small Cap"},
    "CHOICEIN":     {"name": "Choice International Ltd.",                "sector": "Finance",            "cap": "Small Cap"},
    "CHOLAHLDNG":   {"name": "Cholamandalam Financial Holdings Ltd.",    "sector": "Finance",            "cap": "Mid Cap"},
    "CHOLAFIN":     {"name": "Cholamandalam Investment and Finance Company Ltd.", "sector": "Finance",   "cap": "Large Cap"},
    "CIPLA":        {"name": "Cipla Ltd.",                               "sector": "Pharma",             "cap": "Large Cap"},
    "CUB":          {"name": "City Union Bank Ltd.",                     "sector": "Banking",            "cap": "Mid Cap"},
    "CLEAN":        {"name": "Clean Science and Technology Ltd.",        "sector": "Chemicals",          "cap": "Small Cap"},
    "COALINDIA":    {"name": "Coal India Ltd.",                          "sector": "Energy",             "cap": "Large Cap"},
    "COCHINSHIP":   {"name": "Cochin Shipyard Ltd.",                     "sector": "Engineering",        "cap": "Mid Cap"},
    "COFORGE":      {"name": "Coforge Ltd.",                             "sector": "IT",                 "cap": "Mid Cap"},
    "COHANCE":      {"name": "Cohance Lifesciences Ltd.",                "sector": "Pharma",             "cap": "Small Cap"},
    "COLPAL":       {"name": "Colgate Palmolive (India) Ltd.",           "sector": "FMCG",               "cap": "Large Cap"},
    "CAMS":         {"name": "Computer Age Management Services Ltd.",    "sector": "Fintech",            "cap": "Mid Cap"},
    "CONCORDBIO":   {"name": "Concord Biotech Ltd.",                     "sector": "Pharma",             "cap": "Small Cap"},
    "CONCOR":       {"name": "Container Corporation of India Ltd.",      "sector": "Logistics",          "cap": "Mid Cap"},
    "COROMANDEL":   {"name": "Coromandel International Ltd.",            "sector": "Chemicals",          "cap": "Mid Cap"},
    "CRAFTSMAN":    {"name": "Craftsman Automation Ltd.",                "sector": "Auto",               "cap": "Small Cap"},
    "CREDITACC":    {"name": "CreditAccess Grameen Ltd.",                "sector": "Finance",            "cap": "Mid Cap"},
    "CROMPTON":     {"name": "Crompton Greaves Consumer Electricals Ltd.", "sector": "Consumer Durables", "cap": "Mid Cap"},
    "CUMMINSIND":   {"name": "Cummins India Ltd.",                       "sector": "Engineering",        "cap": "Mid Cap"},
    "CYIENT":       {"name": "Cyient Ltd.",                              "sector": "IT",                 "cap": "Mid Cap"},
    "DCMSHRIRAM":   {"name": "DCM Shriram Ltd.",                         "sector": "Diversified",        "cap": "Small Cap"},
    "DLF":          {"name": "DLF Ltd.",                                 "sector": "Real Estate",        "cap": "Large Cap"},
    "DOMINOS":      {"name": "Devyani International Ltd.",               "sector": "Restaurants",        "cap": "Mid Cap"},
    "DOMS":         {"name": "DOMS Industries Ltd.",                     "sector": "Consumer",           "cap": "Small Cap"},
    "DABUR":        {"name": "Dabur India Ltd.",                         "sector": "FMCG",               "cap": "Large Cap"},
    "DALBHARAT":    {"name": "Dalmia Bharat Ltd.",                       "sector": "Cement",             "cap": "Large Cap"},
    "DATAPATTNS":   {"name": "Data Patterns (India) Ltd.",               "sector": "Engineering",        "cap": "Small Cap"},
    "DEEPAKFERT":   {"name": "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "sector": "Chemicals",   "cap": "Small Cap"},
    "DEEPAKNITR":   {"name": "Deepak Nitrite Ltd.",                      "sector": "Chemicals",          "cap": "Mid Cap"},
    "DELHIVERY":    {"name": "Delhivery Ltd.",                           "sector": "Logistics",          "cap": "Mid Cap"},
    "DIVISLAB":     {"name": "Divi's Laboratories Ltd.",                 "sector": "Pharma",             "cap": "Large Cap"},
    "DIXON":        {"name": "Dixon Technologies (India) Ltd.",          "sector": "Consumer Durables",  "cap": "Large Cap"},
    "DRAGARWAL":    {"name": "Dr. Agarwal's Health Care Ltd.",           "sector": "Healthcare",         "cap": "Small Cap"},
    "LALPATHLAB":   {"name": "Dr. Lal Path Labs Ltd.",                   "sector": "Healthcare",         "cap": "Mid Cap"},
    "DRREDDY":      {"name": "Dr. Reddy's Laboratories Ltd.",            "sector": "Pharma",             "cap": "Large Cap"},
    "EIDPARRY":     {"name": "E.I.D. Parry (India) Ltd.",               "sector": "FMCG",               "cap": "Small Cap"},
    "EIHOTEL":      {"name": "EIH Ltd.",                                 "sector": "Hotels",             "cap": "Mid Cap"},
    "EICHERMOT":    {"name": "Eicher Motors Ltd.",                       "sector": "Auto",               "cap": "Large Cap"},
    "ELECON":       {"name": "Elecon Engineering Co. Ltd.",              "sector": "Engineering",        "cap": "Small Cap"},
    "ELGIEQUIP":    {"name": "Elgi Equipments Ltd.",                     "sector": "Engineering",        "cap": "Mid Cap"},
    "EMAMILTD":     {"name": "Emami Ltd.",                               "sector": "FMCG",               "cap": "Mid Cap"},
    "EMCURE":       {"name": "Emcure Pharmaceuticals Ltd.",              "sector": "Pharma",             "cap": "Mid Cap"},
    "ENDURANCE":    {"name": "Endurance Technologies Ltd.",              "sector": "Auto",               "cap": "Mid Cap"},
    "ENGINERSIN":   {"name": "Engineers India Ltd.",                     "sector": "Engineering",        "cap": "Small Cap"},
    "ERIS":         {"name": "Eris Lifesciences Ltd.",                   "sector": "Pharma",             "cap": "Mid Cap"},
    "ESCORTS":      {"name": "Escorts Kubota Ltd.",                      "sector": "Auto",               "cap": "Mid Cap"},
    "ZOMATO":       {"name": "Eternal Ltd.",                             "sector": "Consumer Tech",      "cap": "Large Cap"},
    "EXIDEIND":     {"name": "Exide Industries Ltd.",                    "sector": "Auto",               "cap": "Large Cap"},
    "NYKAA":        {"name": "FSN E-Commerce Ventures Ltd.",             "sector": "Consumer Tech",      "cap": "Large Cap"},
    "FEDERALBNK":   {"name": "Federal Bank Ltd.",                        "sector": "Banking",            "cap": "Mid Cap"},
    "FACT":         {"name": "Fertilisers and Chemicals Travancore Ltd.", "sector": "Chemicals",          "cap": "Small Cap"},
    "FINCABLES":    {"name": "Finolex Cables Ltd.",                      "sector": "Electricals",        "cap": "Mid Cap"},
    "FINPIPE":      {"name": "Finolex Industries Ltd.",                  "sector": "Building Materials", "cap": "Mid Cap"},
    "FSL":          {"name": "Firstsource Solutions Ltd.",               "sector": "IT",                 "cap": "Mid Cap"},
    "FIVESTAR":     {"name": "Five-Star Business Finance Ltd.",          "sector": "Finance",            "cap": "Mid Cap"},
    "FORCEMOT":     {"name": "Force Motors Ltd.",                        "sector": "Auto",               "cap": "Small Cap"},
    "FORTIS":       {"name": "Fortis Healthcare Ltd.",                   "sector": "Healthcare",         "cap": "Mid Cap"},
    "GAIL":         {"name": "GAIL (India) Ltd.",                        "sector": "Energy",             "cap": "Large Cap"},
    "GEVERNOVA":    {"name": "GE Vernova T&D India Ltd.",                "sector": "Engineering",        "cap": "Mid Cap"},
    "GMR":          {"name": "GMR Airports Ltd.",                        "sector": "Infrastructure",     "cap": "Mid Cap"},
    "GRSE":         {"name": "Garden Reach Shipbuilders & Engineers Ltd.", "sector": "Engineering",       "cap": "Mid Cap"},
    "GICRE":        {"name": "General Insurance Corporation of India",   "sector": "Insurance",          "cap": "Mid Cap"},
    "GILLETTE":     {"name": "Gillette India Ltd.",                      "sector": "FMCG",               "cap": "Small Cap"},
    "GLAND":        {"name": "Gland Pharma Ltd.",                        "sector": "Pharma",             "cap": "Mid Cap"},
    "GLAXO":        {"name": "Glaxosmithkline Pharmaceuticals Ltd.",     "sector": "Pharma",             "cap": "Mid Cap"},
    "GLENMARK":     {"name": "Glenmark Pharmaceuticals Ltd.",            "sector": "Pharma",             "cap": "Mid Cap"},
    "MEDANTA":      {"name": "Global Health Ltd.",                       "sector": "Healthcare",         "cap": "Mid Cap"},
    "GODIGIT":      {"name": "Go Digit General Insurance Ltd.",          "sector": "Insurance",          "cap": "Mid Cap"},
    "GODAWARIPOW":  {"name": "Godawari Power & Ispat Ltd.",              "sector": "Metals",             "cap": "Small Cap"},
    "GODFRYPHLP":   {"name": "Godfrey Phillips India Ltd.",              "sector": "FMCG",               "cap": "Small Cap"},
    "GODREJAGRO":   {"name": "Godrej Agrovet Ltd.",                      "sector": "FMCG",               "cap": "Mid Cap"},
    "GODREJCP":     {"name": "Godrej Consumer Products Ltd.",            "sector": "FMCG",               "cap": "Large Cap"},
    "GODREJIND":    {"name": "Godrej Industries Ltd.",                   "sector": "Diversified",        "cap": "Mid Cap"},
    "GODREJPROP":   {"name": "Godrej Properties Ltd.",                   "sector": "Real Estate",        "cap": "Large Cap"},
    "GRANULES":     {"name": "Granules India Ltd.",                      "sector": "Pharma",             "cap": "Small Cap"},
    "GRAPHITE":     {"name": "Graphite India Ltd.",                      "sector": "Industrials",        "cap": "Small Cap"},
    "GRASIM":       {"name": "Grasim Industries Ltd.",                   "sector": "Diversified",        "cap": "Large Cap"},
    "GRAVITA":      {"name": "Gravita India Ltd.",                       "sector": "Metals",             "cap": "Small Cap"},
    "GESHIP":       {"name": "Great Eastern Shipping Co. Ltd.",          "sector": "Shipping",           "cap": "Mid Cap"},
    "FLUOROCHEM":   {"name": "Gujarat Fluorochemicals Ltd.",             "sector": "Chemicals",          "cap": "Mid Cap"},
    "GUJGASLTD":    {"name": "Gujarat Gas Ltd.",                         "sector": "Energy",             "cap": "Large Cap"},
    "GMDC":         {"name": "Gujarat Mineral Development Corporation Ltd.", "sector": "Metals",         "cap": "Small Cap"},
    "GSPL":         {"name": "Gujarat State Petronet Ltd.",              "sector": "Energy",             "cap": "Mid Cap"},
    "HEG":          {"name": "H.E.G. Ltd.",                              "sector": "Industrials",        "cap": "Small Cap"},
    "HBLENGINE":    {"name": "HBL Engineering Ltd.",                     "sector": "Engineering",        "cap": "Small Cap"},
    "HCLTECH":      {"name": "HCL Technologies Ltd.",                    "sector": "IT",                 "cap": "Large Cap"},
    "HDFCAMC":      {"name": "HDFC Asset Management Company Ltd.",       "sector": "Finance",            "cap": "Large Cap"},
    "HDFCBANK":     {"name": "HDFC Bank Ltd.",                           "sector": "Banking",            "cap": "Large Cap"},
    "HDFCLIFE":     {"name": "HDFC Life Insurance Company Ltd.",         "sector": "Insurance",          "cap": "Large Cap"},
    "HFCL":         {"name": "HFCL Ltd.",                                "sector": "Telecom",            "cap": "Small Cap"},
    "HAPPSTMNDS":   {"name": "Happiest Minds Technologies Ltd.",         "sector": "IT",                 "cap": "Mid Cap"},
    "HAVELLS":      {"name": "Havells India Ltd.",                       "sector": "Electricals",        "cap": "Large Cap"},
    "HEROMOTOCO":   {"name": "Hero MotoCorp Ltd.",                       "sector": "Auto",               "cap": "Large Cap"},
    "HEXAWARE":     {"name": "Hexaware Technologies Ltd.",               "sector": "IT",                 "cap": "Mid Cap"},
    "HIMADRI":      {"name": "Himadri Speciality Chemical Ltd.",         "sector": "Chemicals",          "cap": "Small Cap"},
    "HINDALCO":     {"name": "Hindalco Industries Ltd.",                 "sector": "Metals",             "cap": "Large Cap"},
    "HAL":          {"name": "Hindustan Aeronautics Ltd.",               "sector": "Engineering",        "cap": "Large Cap"},
    "HINDCOPPER":   {"name": "Hindustan Copper Ltd.",                    "sector": "Metals",             "cap": "Mid Cap"},
    "HINDPETRO":    {"name": "Hindustan Petroleum Corporation Ltd.",     "sector": "Energy",             "cap": "Large Cap"},
    "HINDUNILVR":   {"name": "Hindustan Unilever Ltd.",                  "sector": "FMCG",               "cap": "Large Cap"},
    "HINDZINC":     {"name": "Hindustan Zinc Ltd.",                      "sector": "Metals",             "cap": "Large Cap"},
    "HITACHIENER":  {"name": "Hitachi Energy India Ltd.",                "sector": "Engineering",        "cap": "Mid Cap"},
    "HOMEFIRST":    {"name": "Home First Finance Company India Ltd.",    "sector": "Finance",            "cap": "Mid Cap"},
    "HONASA":       {"name": "Honasa Consumer Ltd.",                     "sector": "Consumer",           "cap": "Mid Cap"},
    "HONAUT":       {"name": "Honeywell Automation India Ltd.",          "sector": "Industrials",        "cap": "Mid Cap"},
    "HUDCO":        {"name": "Housing & Urban Development Corporation Ltd.", "sector": "Finance",        "cap": "Large Cap"},
    "HYUNDAI":      {"name": "Hyundai Motor India Ltd.",                 "sector": "Auto",               "cap": "Large Cap"},
    "ICICIBANK":    {"name": "ICICI Bank Ltd.",                          "sector": "Banking",            "cap": "Large Cap"},
    "ICICIGI":      {"name": "ICICI Lombard General Insurance Company Ltd.", "sector": "Insurance",      "cap": "Large Cap"},
    "ICICIPRULI":   {"name": "ICICI Prudential Life Insurance Company Ltd.", "sector": "Insurance",      "cap": "Large Cap"},
    "IDBI":         {"name": "IDBI Bank Ltd.",                           "sector": "Banking",            "cap": "Mid Cap"},
    "IDFCFIRSTB":   {"name": "IDFC First Bank Ltd.",                     "sector": "Banking",            "cap": "Large Cap"},
    "IFCI":         {"name": "IFCI Ltd.",                                "sector": "Finance",            "cap": "Small Cap"},
    "IIFL":         {"name": "IIFL Finance Ltd.",                        "sector": "Finance",            "cap": "Mid Cap"},
    "INOXINDIA":    {"name": "INOX India Ltd.",                          "sector": "Industrials",        "cap": "Small Cap"},
    "IRB":          {"name": "IRB Infrastructure Developers Ltd.",       "sector": "Infrastructure",     "cap": "Mid Cap"},
    "IRCON":        {"name": "IRCON International Ltd.",                 "sector": "Infrastructure",     "cap": "Mid Cap"},
    "ITCHOTEL":     {"name": "ITC Hotels Ltd.",                          "sector": "Hotels",             "cap": "Mid Cap"},
    "ITC":          {"name": "ITC Ltd.",                                 "sector": "FMCG",               "cap": "Large Cap"},
    "ITI":          {"name": "ITI Ltd.",                                 "sector": "Telecom",            "cap": "Small Cap"},
    "INDEGENE":     {"name": "Indegene Ltd.",                            "sector": "IT",                 "cap": "Mid Cap"},
    "INDIACEM":     {"name": "India Cements Ltd.",                       "sector": "Cement",             "cap": "Mid Cap"},
    "INDIAMART":    {"name": "Indiamart Intermesh Ltd.",                 "sector": "Consumer Tech",      "cap": "Mid Cap"},
    "INDIANB":      {"name": "Indian Bank",                              "sector": "Banking",            "cap": "Mid Cap"},
    "IEX":          {"name": "Indian Energy Exchange Ltd.",              "sector": "Fintech",            "cap": "Mid Cap"},
    "INDHOTEL":     {"name": "Indian Hotels Co. Ltd.",                   "sector": "Hotels",             "cap": "Large Cap"},
    "IOC":          {"name": "Indian Oil Corporation Ltd.",              "sector": "Energy",             "cap": "Large Cap"},
    "IOB":          {"name": "Indian Overseas Bank",                     "sector": "Banking",            "cap": "Mid Cap"},
    "IRCTC":        {"name": "Indian Railway Catering And Tourism Corporation Ltd.", "sector": "Services", "cap": "Large Cap"},
    "IRFC":         {"name": "Indian Railway Finance Corporation Ltd.",  "sector": "Finance",            "cap": "Large Cap"},
    "IREDA":        {"name": "Indian Renewable Energy Development Agency Ltd.", "sector": "Finance",     "cap": "Mid Cap"},
    "IGL":          {"name": "Indraprastha Gas Ltd.",                    "sector": "Energy",             "cap": "Large Cap"},
    "INDUSTOWER":   {"name": "Indus Towers Ltd.",                        "sector": "Telecom",            "cap": "Large Cap"},
    "INDUSINDBK":   {"name": "IndusInd Bank Ltd.",                       "sector": "Banking",            "cap": "Large Cap"},
    "NAUKRI":       {"name": "Info Edge (India) Ltd.",                   "sector": "Consumer Tech",      "cap": "Large Cap"},
    "INFY":         {"name": "Infosys Ltd.",                             "sector": "IT",                 "cap": "Large Cap"},
    "INOXWIND":     {"name": "Inox Wind Ltd.",                           "sector": "Power",              "cap": "Small Cap"},
    "INTELLECT":    {"name": "Intellect Design Arena Ltd.",              "sector": "IT",                 "cap": "Mid Cap"},
    "INDIGO":       {"name": "InterGlobe Aviation Ltd.",                 "sector": "Aviation",           "cap": "Large Cap"},
    "IGI":          {"name": "International Gemmological Institute (India) Ltd.", "sector": "Services",  "cap": "Small Cap"},
    "INVENTURUS":   {"name": "Inventurus Knowledge Solutions Ltd.",      "sector": "IT",                 "cap": "Small Cap"},
    "IPCALAB":      {"name": "Ipca Laboratories Ltd.",                   "sector": "Pharma",             "cap": "Mid Cap"},
    "JBCHEPHARM":   {"name": "J.B. Chemicals & Pharmaceuticals Ltd.",    "sector": "Pharma",             "cap": "Mid Cap"},
    "JKCEMENT":     {"name": "J.K. Cement Ltd.",                         "sector": "Cement",             "cap": "Mid Cap"},
    "JBMA":         {"name": "JBM Auto Ltd.",                            "sector": "Auto",               "cap": "Small Cap"},
    "JKTYRE":       {"name": "JK Tyre & Industries Ltd.",                "sector": "Auto",               "cap": "Small Cap"},
    "JMFINANCIL":   {"name": "JM Financial Ltd.",                        "sector": "Finance",            "cap": "Small Cap"},
    "JSWENERGY":    {"name": "JSW Energy Ltd.",                          "sector": "Power",              "cap": "Large Cap"},
    "JSWINFRA":     {"name": "JSW Infrastructure Ltd.",                  "sector": "Infrastructure",     "cap": "Large Cap"},
    "JSWSTEEL":     {"name": "JSW Steel Ltd.",                           "sector": "Metals",             "cap": "Large Cap"},
    "JPPOWER":      {"name": "Jaiprakash Power Ventures Ltd.",           "sector": "Power",              "cap": "Small Cap"},
    "J&KBANK":      {"name": "Jammu & Kashmir Bank Ltd.",                "sector": "Banking",            "cap": "Small Cap"},
    "JINDALSAW":    {"name": "Jindal Saw Ltd.",                          "sector": "Metals",             "cap": "Small Cap"},
    "JINDALSTEL":   {"name": "Jindal Stainless Ltd.",                    "sector": "Metals",             "cap": "Mid Cap"},
    "JSL":          {"name": "Jindal Steel Ltd.",                        "sector": "Metals",             "cap": "Mid Cap"},
    "JIOFIN":       {"name": "Jio Financial Services Ltd.",              "sector": "Finance",            "cap": "Large Cap"},
    "JUBLFOOD":     {"name": "Jubilant Foodworks Ltd.",                  "sector": "Restaurants",        "cap": "Mid Cap"},
    "JUBLINGREA":   {"name": "Jubilant Ingrevia Ltd.",                   "sector": "Chemicals",          "cap": "Mid Cap"},
    "JUBLPHARMA":   {"name": "Jubilant Pharmova Ltd.",                   "sector": "Pharma",             "cap": "Small Cap"},
    "JUPITERWAG":   {"name": "Jupiter Wagons Ltd.",                      "sector": "Engineering",        "cap": "Small Cap"},
    "JYOTHYLAB":    {"name": "Jyothy Labs Ltd.",                         "sector": "FMCG",               "cap": "Mid Cap"},
    "JYOTICNC":     {"name": "Jyoti CNC Automation Ltd.",               "sector": "Engineering",        "cap": "Small Cap"},
    "KPR":          {"name": "K.P.R. Mill Ltd.",                         "sector": "Textiles",           "cap": "Mid Cap"},
    "KEI":          {"name": "KEI Industries Ltd.",                      "sector": "Electricals",        "cap": "Mid Cap"},
    "KPITTECH":     {"name": "KPIT Technologies Ltd.",                   "sector": "IT",                 "cap": "Mid Cap"},
    "KSB":          {"name": "KSB Ltd.",                                 "sector": "Engineering",        "cap": "Small Cap"},
    "KAJARIACER":   {"name": "Kajaria Ceramics Ltd.",                    "sector": "Building Materials", "cap": "Mid Cap"},
    "KALPATPOWR":   {"name": "Kalpataru Projects International Ltd.",    "sector": "Infrastructure",     "cap": "Mid Cap"},
    "KALYANKJIL":   {"name": "Kalyan Jewellers India Ltd.",              "sector": "Consumer",           "cap": "Mid Cap"},
    "KARURVYSYA":   {"name": "Karur Vysya Bank Ltd.",                    "sector": "Banking",            "cap": "Mid Cap"},
    "KAYNES":       {"name": "Kaynes Technology India Ltd.",             "sector": "Engineering",        "cap": "Mid Cap"},
    "KECL":         {"name": "Kec International Ltd.",                   "sector": "Engineering",        "cap": "Mid Cap"},
    "KFINTECH":     {"name": "Kfin Technologies Ltd.",                   "sector": "Fintech",            "cap": "Mid Cap"},
    "KIRLOSBROS":   {"name": "Kirloskar Brothers Ltd.",                  "sector": "Engineering",        "cap": "Small Cap"},
    "KIRLOSENG":    {"name": "Kirloskar Oil Eng Ltd.",                   "sector": "Engineering",        "cap": "Small Cap"},
    "KOTAKBANK":    {"name": "Kotak Mahindra Bank Ltd.",                 "sector": "Banking",            "cap": "Large Cap"},
    "KIMS":         {"name": "Krishna Institute of Medical Sciences Ltd.", "sector": "Healthcare",        "cap": "Mid Cap"},
    "L&TFH":        {"name": "L&T Finance Ltd.",                         "sector": "Finance",            "cap": "Large Cap"},
    "LTTS":         {"name": "L&T Technology Services Ltd.",             "sector": "IT",                 "cap": "Mid Cap"},
    "LICHSGFIN":    {"name": "LIC Housing Finance Ltd.",                 "sector": "Finance",            "cap": "Large Cap"},
    "LTFOODS":      {"name": "LT Foods Ltd.",                            "sector": "FMCG",               "cap": "Small Cap"},
    "LTIM":         {"name": "LTIMindtree Ltd.",                         "sector": "IT",                 "cap": "Large Cap"},
    "LT":           {"name": "Larsen & Toubro Ltd.",                     "sector": "Infrastructure",     "cap": "Large Cap"},
    "LATENTVIEW":   {"name": "Latent View Analytics Ltd.",               "sector": "IT",                 "cap": "Small Cap"},
    "LAURUSLABS":   {"name": "Laurus Labs Ltd.",                         "sector": "Pharma",             "cap": "Mid Cap"},
    "LEELAHOT":     {"name": "Leela Palaces Hotels & Resorts Ltd.",      "sector": "Hotels",             "cap": "Mid Cap"},
    "LEMONTREE":    {"name": "Lemon Tree Hotels Ltd.",                   "sector": "Hotels",             "cap": "Mid Cap"},
    "LICI":         {"name": "Life Insurance Corporation of India",      "sector": "Insurance",          "cap": "Large Cap"},
    "LINDEINDIA":   {"name": "Linde India Ltd.",                         "sector": "Chemicals",          "cap": "Mid Cap"},
    "LLOYDSME":     {"name": "Lloyds Metals And Energy Ltd.",            "sector": "Metals",             "cap": "Small Cap"},
    "MACROTECH":    {"name": "Lodha Developers Ltd.",                    "sector": "Real Estate",        "cap": "Large Cap"},
    "LUPIN":        {"name": "Lupin Ltd.",                               "sector": "Pharma",             "cap": "Large Cap"},
    "MMTC":         {"name": "MMTC Ltd.",                                "sector": "Metals",             "cap": "Small Cap"},
    "MRF":          {"name": "MRF Ltd.",                                 "sector": "Auto",               "cap": "Large Cap"},
    "MGL":          {"name": "Mahanagar Gas Ltd.",                       "sector": "Energy",             "cap": "Large Cap"},
    "M&M":          {"name": "Mahindra & Mahindra Ltd.",                 "sector": "Auto",               "cap": "Large Cap"},
    "M&MFIN":       {"name": "Mahindra & Mahindra Financial Services Ltd.", "sector": "Finance",         "cap": "Mid Cap"},
    "MANAPPURAM":   {"name": "Manappuram Finance Ltd.",                  "sector": "Finance",            "cap": "Mid Cap"},
    "MRPL":         {"name": "Mangalore Refinery & Petrochemicals Ltd.", "sector": "Energy",             "cap": "Mid Cap"},
    "MANKIND":      {"name": "Mankind Pharma Ltd.",                      "sector": "Pharma",             "cap": "Large Cap"},
    "MARICO":       {"name": "Marico Ltd.",                              "sector": "FMCG",               "cap": "Large Cap"},
    "MARUTI":       {"name": "Maruti Suzuki India Ltd.",                 "sector": "Auto",               "cap": "Large Cap"},
    "MFSL":         {"name": "Max Financial Services Ltd.",              "sector": "Insurance",          "cap": "Mid Cap"},
    "MAXHEALTH":    {"name": "Max Healthcare Institute Ltd.",            "sector": "Healthcare",         "cap": "Large Cap"},
    "MAZDOCK":      {"name": "Mazagoan Dock Shipbuilders Ltd.",          "sector": "Engineering",        "cap": "Mid Cap"},
    "METROPOLIS":   {"name": "Metropolis Healthcare Ltd.",               "sector": "Healthcare",         "cap": "Mid Cap"},
    "MINDACORP":    {"name": "Minda Corporation Ltd.",                   "sector": "Auto",               "cap": "Small Cap"},
    "MOTHERSON":    {"name": "Samvardhana Motherson International Ltd.", "sector": "Auto",               "cap": "Large Cap"},
    "MOTILALOFS":   {"name": "Motilal Oswal Financial Services Ltd.",    "sector": "Fintech",            "cap": "Mid Cap"},
    "MPHASIS":      {"name": "MphasiS Ltd.",                             "sector": "IT",                 "cap": "Mid Cap"},
    "MCX":          {"name": "Multi Commodity Exchange of India Ltd.",   "sector": "Fintech",            "cap": "Mid Cap"},
    "MUTHOOTFIN":   {"name": "Muthoot Finance Ltd.",                     "sector": "Finance",            "cap": "Large Cap"},
    "NATCOPHARM":   {"name": "NATCO Pharma Ltd.",                        "sector": "Pharma",             "cap": "Small Cap"},
    "NBCC":         {"name": "NBCC (India) Ltd.",                        "sector": "Infrastructure",     "cap": "Mid Cap"},
    "NCC":          {"name": "NCC Ltd.",                                 "sector": "Infrastructure",     "cap": "Mid Cap"},
    "NHPC":         {"name": "NHPC Ltd.",                                "sector": "Power",              "cap": "Large Cap"},
    "NLCINDIA":     {"name": "NLC India Ltd.",                           "sector": "Power",              "cap": "Mid Cap"},
    "NMDC":         {"name": "NMDC Ltd.",                                "sector": "Metals",             "cap": "Large Cap"},
    "NMDCSTEEL":    {"name": "NMDC Steel Ltd.",                          "sector": "Metals",             "cap": "Small Cap"},
    "NTPCGREEN":    {"name": "NTPC Green Energy Ltd.",                   "sector": "Power",              "cap": "Large Cap"},
    "NTPC":         {"name": "NTPC Ltd.",                                "sector": "Power",              "cap": "Large Cap"},
    "NH":           {"name": "Narayana Hrudayalaya Ltd.",                "sector": "Healthcare",         "cap": "Mid Cap"},
    "NATIONALUM":   {"name": "National Aluminium Co. Ltd.",              "sector": "Metals",             "cap": "Large Cap"},
    "NAVINFLUOR":   {"name": "Navin Fluorine International Ltd.",        "sector": "Chemicals",          "cap": "Mid Cap"},
    "NESTLEIND":    {"name": "Nestle India Ltd.",                        "sector": "FMCG",               "cap": "Large Cap"},
    "NETWEB":       {"name": "Netweb Technologies India Ltd.",           "sector": "IT",                 "cap": "Small Cap"},
    "NEULANDLAB":   {"name": "Neuland Laboratories Ltd.",                "sector": "Pharma",             "cap": "Small Cap"},
    "NEWGEN":       {"name": "Newgen Software Technologies Ltd.",        "sector": "IT",                 "cap": "Mid Cap"},
    "NAM-INDIA":    {"name": "Nippon Life India Asset Management Ltd.",  "sector": "Finance",            "cap": "Mid Cap"},
    "NIVABUPA":     {"name": "Niva Bupa Health Insurance Company Ltd.",  "sector": "Insurance",          "cap": "Mid Cap"},
    "NUVAMA":       {"name": "Nuvama Wealth Management Ltd.",            "sector": "Fintech",            "cap": "Mid Cap"},
    "NUVOCO":       {"name": "Nuvoco Vistas Corporation Ltd.",           "sector": "Cement",             "cap": "Mid Cap"},
    "OBEROIRLTY":   {"name": "Oberoi Realty Ltd.",                       "sector": "Real Estate",        "cap": "Large Cap"},
    "ONGC":         {"name": "Oil & Natural Gas Corporation Ltd.",       "sector": "Energy",             "cap": "Large Cap"},
    "OIL":          {"name": "Oil India Ltd.",                           "sector": "Energy",             "cap": "Large Cap"},
    "OLAELEC":      {"name": "Ola Electric Mobility Ltd.",               "sector": "Auto",               "cap": "Mid Cap"},
    "OLECTRA":      {"name": "Olectra Greentech Ltd.",                   "sector": "Auto",               "cap": "Small Cap"},
    "PAYTM":        {"name": "One 97 Communications Ltd.",               "sector": "Fintech",            "cap": "Mid Cap"},
    "ONESOURCE":    {"name": "Onesource Specialty Pharma Ltd.",          "sector": "Pharma",             "cap": "Small Cap"},
    "OFSS":         {"name": "Oracle Financial Services Software Ltd.",  "sector": "IT",                 "cap": "Large Cap"},
    "POLICYBZR":    {"name": "PB Fintech Ltd.",                          "sector": "Fintech",            "cap": "Mid Cap"},
    "PCBL":         {"name": "PCBL Chemical Ltd.",                       "sector": "Chemicals",          "cap": "Mid Cap"},
    "PGEL":         {"name": "PG Electroplast Ltd.",                     "sector": "Consumer Durables",  "cap": "Small Cap"},
    "PIIND":        {"name": "PI Industries Ltd.",                       "sector": "Chemicals",          "cap": "Mid Cap"},
    "PNBHOUSING":   {"name": "PNB Housing Finance Ltd.",                 "sector": "Finance",            "cap": "Mid Cap"},
    "PTCIND":       {"name": "PTC Industries Ltd.",                      "sector": "Metals",             "cap": "Small Cap"},
    "PVRINOX":      {"name": "PVR INOX Ltd.",                            "sector": "Entertainment",      "cap": "Mid Cap"},
    "PAGEIND":      {"name": "Page Industries Ltd.",                     "sector": "Textiles",           "cap": "Mid Cap"},
    "PATANJALI":    {"name": "Patanjali Foods Ltd.",                     "sector": "FMCG",               "cap": "Mid Cap"},
    "PERSISTENT":   {"name": "Persistent Systems Ltd.",                  "sector": "IT",                 "cap": "Large Cap"},
    "PETRONET":     {"name": "Petronet LNG Ltd.",                        "sector": "Energy",             "cap": "Large Cap"},
    "PFIZER":       {"name": "Pfizer Ltd.",                              "sector": "Pharma",             "cap": "Mid Cap"},
    "PHOENIXLTD":   {"name": "Phoenix Mills Ltd.",                       "sector": "Real Estate",        "cap": "Large Cap"},
    "PIDILITIND":   {"name": "Pidilite Industries Ltd.",                 "sector": "Chemicals",          "cap": "Large Cap"},
    "PIRAMALPHA":   {"name": "Piramal Pharma Ltd.",                      "sector": "Pharma",             "cap": "Mid Cap"},
    "POLYMED":      {"name": "Poly Medicure Ltd.",                       "sector": "Healthcare",         "cap": "Small Cap"},
    "POLYCAB":      {"name": "Polycab India Ltd.",                       "sector": "Electricals",        "cap": "Large Cap"},
    "POONAWALLA":   {"name": "Poonawalla Fincorp Ltd.",                  "sector": "Finance",            "cap": "Mid Cap"},
    "PFC":          {"name": "Power Finance Corporation Ltd.",           "sector": "Finance",            "cap": "Large Cap"},
    "POWERGRID":    {"name": "Power Grid Corporation of India Ltd.",     "sector": "Power",              "cap": "Large Cap"},
    "PRAJIND":      {"name": "Praj Industries Ltd.",                     "sector": "Engineering",        "cap": "Small Cap"},
    "PREMIERENER":  {"name": "Premier Energies Ltd.",                    "sector": "Power",              "cap": "Mid Cap"},
    "PRESTIGE":     {"name": "Prestige Estates Projects Ltd.",           "sector": "Real Estate",        "cap": "Large Cap"},
    "PGHH":         {"name": "Procter & Gamble Hygiene & Health Care Ltd.", "sector": "FMCG",            "cap": "Mid Cap"},
    "PNB":          {"name": "Punjab National Bank",                     "sector": "Banking",            "cap": "Large Cap"},
    "RRKABEL":      {"name": "R R Kabel Ltd.",                           "sector": "Electricals",        "cap": "Small Cap"},
    "RBLBANK":      {"name": "RBL Bank Ltd.",                            "sector": "Banking",            "cap": "Mid Cap"},
    "RECLTD":       {"name": "REC Ltd.",                                 "sector": "Finance",            "cap": "Large Cap"},
    "RHIM":         {"name": "RHI MAGNESITA INDIA LTD.",                 "sector": "Industrials",        "cap": "Small Cap"},
    "RITES":        {"name": "RITES Ltd.",                               "sector": "Engineering",        "cap": "Mid Cap"},
    "RADICO":       {"name": "Radico Khaitan Ltd",                       "sector": "FMCG",               "cap": "Mid Cap"},
    "RVNL":         {"name": "Rail Vikas Nigam Ltd.",                    "sector": "Infrastructure",     "cap": "Large Cap"},
    "RAILTEL":      {"name": "Railtel Corporation Of India Ltd.",        "sector": "IT",                 "cap": "Small Cap"},
    "RAINBOW":      {"name": "Rainbow Childrens Medicare Ltd.",          "sector": "Healthcare",         "cap": "Small Cap"},
    "RAMKRISHNA":   {"name": "Ramkrishna Forgings Ltd.",                 "sector": "Metals",             "cap": "Small Cap"},
    "RCFLTD":       {"name": "Rashtriya Chemicals & Fertilizers Ltd.",   "sector": "Chemicals",          "cap": "Small Cap"},
    "REDINGTON":    {"name": "Redington Ltd.",                           "sector": "IT",                 "cap": "Mid Cap"},
    "RELIANCE":     {"name": "Reliance Industries Ltd.",                 "sector": "Energy",             "cap": "Large Cap"},
    "RINFRA":       {"name": "Reliance Infrastructure Ltd.",             "sector": "Infrastructure",     "cap": "Small Cap"},
    "RPOWER":       {"name": "Reliance Power Ltd.",                      "sector": "Power",              "cap": "Small Cap"},
    "SBFC":         {"name": "SBFC Finance Ltd.",                        "sector": "Finance",            "cap": "Small Cap"},
    "SBICARD":      {"name": "SBI Cards and Payment Services Ltd.",      "sector": "Finance",            "cap": "Large Cap"},
    "SBILIFE":      {"name": "SBI Life Insurance Company Ltd.",          "sector": "Insurance",          "cap": "Large Cap"},
    "SJVN":         {"name": "SJVN Ltd.",                                "sector": "Power",              "cap": "Mid Cap"},
    "SKFINDIA":     {"name": "SKF India Ltd.",                           "sector": "Industrials",        "cap": "Mid Cap"},
    "SRF":          {"name": "SRF Ltd.",                                 "sector": "Chemicals",          "cap": "Large Cap"},
    "SAGILITY":     {"name": "Sagility Ltd.",                            "sector": "IT",                 "cap": "Mid Cap"},
    "SAILIFESCI":   {"name": "Sai Life Sciences Ltd.",                   "sector": "Pharma",             "cap": "Small Cap"},
    "SAMMAAN":      {"name": "Sammaan Capital Ltd.",                     "sector": "Finance",            "cap": "Small Cap"},
    "SAPPHIRE":     {"name": "Sapphire Foods India Ltd.",                "sector": "Restaurants",        "cap": "Small Cap"},
    "SARDAEN":      {"name": "Sarda Energy and Minerals Ltd.",           "sector": "Metals",             "cap": "Small Cap"},
    "SAREGAMA":     {"name": "Saregama India Ltd",                       "sector": "Media",              "cap": "Small Cap"},
    "SCHAEFFLER":   {"name": "Schaeffler India Ltd.",                    "sector": "Industrials",        "cap": "Mid Cap"},
    "SCHNEIDER":    {"name": "Schneider Electric Infrastructure Ltd.",   "sector": "Engineering",        "cap": "Small Cap"},
    "SCI":          {"name": "Shipping Corporation of India Ltd.",       "sector": "Shipping",           "cap": "Small Cap"},
    "SHREECEM":     {"name": "Shree Cement Ltd.",                        "sector": "Cement",             "cap": "Large Cap"},
    "SHRIRAMFIN":   {"name": "Shriram Finance Ltd.",                     "sector": "Finance",            "cap": "Large Cap"},
    "SHYAMMETL":    {"name": "Shyam Metalics and Energy Ltd.",          "sector": "Metals",             "cap": "Mid Cap"},
    "SIEMENSENER":  {"name": "Siemens Energy India Ltd.",                "sector": "Engineering",        "cap": "Mid Cap"},
    "SIEMENS":      {"name": "Siemens Ltd.",                             "sector": "Engineering",        "cap": "Large Cap"},
    "SIGNATURE":    {"name": "Signatureglobal (India) Ltd.",             "sector": "Real Estate",        "cap": "Small Cap"},
    "SOBHA":        {"name": "Sobha Ltd.",                               "sector": "Real Estate",        "cap": "Mid Cap"},
    "SOLARINDS":    {"name": "Solar Industries India Ltd.",              "sector": "Chemicals",          "cap": "Mid Cap"},
    "SONACOMS":     {"name": "Sona BLW Precision Forgings Ltd.",         "sector": "Auto",               "cap": "Mid Cap"},
    "SONATSOFTW":   {"name": "Sonata Software Ltd.",                     "sector": "IT",                 "cap": "Mid Cap"},
    "STARHEALTH":   {"name": "Star Health and Allied Insurance Company Ltd.", "sector": "Insurance",     "cap": "Mid Cap"},
    "SBIN":         {"name": "State Bank of India",                      "sector": "Banking",            "cap": "Large Cap"},
    "SAIL":         {"name": "Steel Authority of India Ltd.",            "sector": "Metals",             "cap": "Large Cap"},
    "SUMICHEM":     {"name": "Sumitomo Chemical India Ltd.",             "sector": "Chemicals",          "cap": "Mid Cap"},
    "SUNPHARMA":    {"name": "Sun Pharmaceutical Industries Ltd.",       "sector": "Pharma",             "cap": "Large Cap"},
    "SUNTV":        {"name": "Sun TV Network Ltd.",                      "sector": "Media",              "cap": "Mid Cap"},
    "SUNDARMFIN":   {"name": "Sundaram Finance Ltd.",                    "sector": "Finance",            "cap": "Mid Cap"},
    "SUNDRMFAST":   {"name": "Sundram Fasteners Ltd.",                   "sector": "Auto",               "cap": "Mid Cap"},
    "SUPREMEIND":   {"name": "Supreme Industries Ltd.",                  "sector": "Building Materials", "cap": "Mid Cap"},
    "SUZLON":       {"name": "Suzlon Energy Ltd.",                       "sector": "Power",              "cap": "Mid Cap"},
    "SWIGGY":       {"name": "Swiggy Ltd.",                              "sector": "Consumer Tech",      "cap": "Mid Cap"},
    "SYNGENE":      {"name": "Syngene International Ltd.",               "sector": "Pharma",             "cap": "Mid Cap"},
    "SYRMA":        {"name": "Syrma SGS Technology Ltd.",                "sector": "Engineering",        "cap": "Small Cap"},
    "TBOTEK":       {"name": "TBO Tek Ltd.",                             "sector": "Consumer Tech",      "cap": "Small Cap"},
    "TVSMOTOR":     {"name": "TVS Motor Company Ltd.",                   "sector": "Auto",               "cap": "Large Cap"},
    "TATACHEM":     {"name": "Tata Chemicals Ltd.",                      "sector": "Chemicals",          "cap": "Large Cap"},
    "TATACOMM":     {"name": "Tata Communications Ltd.",                 "sector": "Telecom",            "cap": "Large Cap"},
    "TCS":          {"name": "Tata Consultancy Services Ltd.",           "sector": "IT",                 "cap": "Large Cap"},
    "TATACONSUM":   {"name": "Tata Consumer Products Ltd.",              "sector": "FMCG",               "cap": "Large Cap"},
    "TATAELXSI":    {"name": "Tata Elxsi Ltd.",                          "sector": "IT",                 "cap": "Large Cap"},
    "TATAINVEST":   {"name": "Tata Investment Corporation Ltd.",         "sector": "Finance",            "cap": "Mid Cap"},
    "TATAMTRDVR":   {"name": "Tata Motors Passenger Vehicles Ltd.",      "sector": "Auto",               "cap": "Large Cap"},
    "TATAPOWER":    {"name": "Tata Power Co. Ltd.",                      "sector": "Power",              "cap": "Large Cap"},
    "TATASTEEL":    {"name": "Tata Steel Ltd.",                          "sector": "Metals",             "cap": "Large Cap"},
    "TATATECH":     {"name": "Tata Technologies Ltd.",                   "sector": "IT",                 "cap": "Mid Cap"},
    "TTML":         {"name": "Tata Teleservices (Maharashtra) Ltd.",     "sector": "Telecom",            "cap": "Small Cap"},
    "TECHM":        {"name": "Tech Mahindra Ltd.",                       "sector": "IT",                 "cap": "Large Cap"},
    "TECHNO":       {"name": "Techno Electric & Engineering Company Ltd.", "sector": "Engineering",       "cap": "Small Cap"},
    "TEJASNET":     {"name": "Tejas Networks Ltd.",                      "sector": "Telecom",            "cap": "Small Cap"},
    "NIACL":        {"name": "The New India Assurance Company Ltd.",     "sector": "Insurance",          "cap": "Mid Cap"},
    "RAMCOCEM":     {"name": "The Ramco Cements Ltd.",                   "sector": "Cement",             "cap": "Mid Cap"},
    "THERMAX":      {"name": "Thermax Ltd.",                             "sector": "Engineering",        "cap": "Mid Cap"},
    "TIMKEN":       {"name": "Timken India Ltd.",                        "sector": "Industrials",        "cap": "Mid Cap"},
    "TITAGARH":     {"name": "Titagarh Rail Systems Ltd.",               "sector": "Engineering",        "cap": "Small Cap"},
    "TITAN":        {"name": "Titan Company Ltd.",                       "sector": "Consumer",           "cap": "Large Cap"},
    "TORNTPHARM":   {"name": "Torrent Pharmaceuticals Ltd.",             "sector": "Pharma",             "cap": "Large Cap"},
    "TORNTPOWER":   {"name": "Torrent Power Ltd.",                       "sector": "Power",              "cap": "Large Cap"},
    "TARIL":        {"name": "Transformers And Rectifiers (India) Ltd.", "sector": "Engineering",        "cap": "Small Cap"},
    "TRENT":        {"name": "Trent Ltd.",                               "sector": "Retail",             "cap": "Large Cap"},
    "TRIDENT":      {"name": "Trident Ltd.",                             "sector": "Textiles",           "cap": "Mid Cap"},
    "TRIVENI":      {"name": "Triveni Engineering & Industries Ltd.",    "sector": "FMCG",               "cap": "Small Cap"},
    "TRITURBINE":   {"name": "Triveni Turbine Ltd.",                     "sector": "Engineering",        "cap": "Small Cap"},
    "TIINDIA":      {"name": "Tube Investments of India Ltd.",           "sector": "Auto",               "cap": "Mid Cap"},
    "UCOBANK":      {"name": "UCO Bank",                                 "sector": "Banking",            "cap": "Small Cap"},
    "UNOMINDA":     {"name": "UNO Minda Ltd.",                           "sector": "Auto",               "cap": "Mid Cap"},
    "UPL":          {"name": "UPL Ltd.",                                 "sector": "Chemicals",          "cap": "Large Cap"},
    "UTIAMC":       {"name": "UTI Asset Management Company Ltd.",        "sector": "Finance",            "cap": "Mid Cap"},
    "ULTRACEMCO":   {"name": "UltraTech Cement Ltd.",                    "sector": "Cement",             "cap": "Large Cap"},
    "UNIONBANK":    {"name": "Union Bank of India",                      "sector": "Banking",            "cap": "Large Cap"},
    "UBL":          {"name": "United Breweries Ltd.",                    "sector": "FMCG",               "cap": "Mid Cap"},
    "UNITDSPR":     {"name": "United Spirits Ltd.",                      "sector": "FMCG",               "cap": "Mid Cap"},
    "USHAMART":     {"name": "Usha Martin Ltd.",                         "sector": "Metals",             "cap": "Small Cap"},
    "VGUARD":       {"name": "V-Guard Industries Ltd.",                  "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "VALORSTATE":   {"name": "Valor Estate Ltd.",                        "sector": "Real Estate",        "cap": "Small Cap"},
    "VARDHMAN":     {"name": "Vardhman Textiles Ltd.",                   "sector": "Textiles",           "cap": "Mid Cap"},
    "VBL":          {"name": "Varun Beverages Ltd.",                     "sector": "FMCG",               "cap": "Large Cap"},
    "MANYAVAR":     {"name": "Vedant Fashions Ltd.",                     "sector": "Consumer",           "cap": "Mid Cap"},
    "VEDL":         {"name": "Vedanta Ltd.",                             "sector": "Metals",             "cap": "Large Cap"},
    "VENTIVE":      {"name": "Ventive Hospitality Ltd.",                 "sector": "Hotels",             "cap": "Small Cap"},
    "VIJAYA":       {"name": "Vijaya Diagnostic Centre Ltd.",            "sector": "Healthcare",         "cap": "Small Cap"},
    "VISHAL":       {"name": "Vishal Mega Mart Ltd.",                    "sector": "Retail",             "cap": "Mid Cap"},
    "IDEA":         {"name": "Vodafone Idea Ltd.",                       "sector": "Telecom",            "cap": "Large Cap"},
    "VOLTAS":       {"name": "Voltas Ltd.",                              "sector": "Consumer Durables",  "cap": "Large Cap"},
    "WAAREEENER":   {"name": "Waaree Energies Ltd.",                     "sector": "Power",              "cap": "Mid Cap"},
    "WELCORP":      {"name": "Welspun Corp Ltd.",                        "sector": "Metals",             "cap": "Mid Cap"},
    "WELSPUNLIV":   {"name": "Welspun Living Ltd.",                      "sector": "Textiles",           "cap": "Mid Cap"},
    "WHIRLPOOL":    {"name": "Whirlpool of India Ltd.",                  "sector": "Consumer Durables",  "cap": "Mid Cap"},
    "WIPRO":        {"name": "Wipro Ltd.",                               "sector": "IT",                 "cap": "Large Cap"},
    "WOCKPHARMA":   {"name": "Wockhardt Ltd.",                           "sector": "Pharma",             "cap": "Small Cap"},
    "YESBANK":      {"name": "Yes Bank Ltd.",                            "sector": "Banking",            "cap": "Mid Cap"},
    "ZFCVINDIA":    {"name": "ZF Commercial Vehicle Control Systems India Ltd.", "sector": "Auto",       "cap": "Small Cap"},
    "ZEEL":         {"name": "Zee Entertainment Enterprises Ltd.",       "sector": "Media",              "cap": "Mid Cap"},
    "ZENTEC":       {"name": "Zen Technologies Ltd.",                    "sector": "Engineering",        "cap": "Small Cap"},
    "ZENSAR":       {"name": "Zensar Technolgies Ltd.",                  "sector": "IT",                 "cap": "Mid Cap"},
    "ZYDUSLIFE":    {"name": "Zydus Lifesciences Ltd.",                  "sector": "Pharma",             "cap": "Large Cap"},
    "ECLERX":       {"name": "eClerx Services Ltd.",                     "sector": "IT",                 "cap": "Mid Cap"},
}


def get_all_symbols(): return list(NIFTY500_STOCKS.keys())


def get_symbols_by_cap(cap): return [
    s for s, d in NIFTY500_STOCKS.items() if d["cap"] == cap]


def get_symbols_by_sector(s): return [
    sym for sym, d in NIFTY500_STOCKS.items() if d["sector"] == s]


def get_all_caps(): return sorted(
    set(d["cap"] for d in NIFTY500_STOCKS.values()))
def get_all_sectors(): return sorted(
    set(d["sector"] for d in NIFTY500_STOCKS.values()))


def get_stock_info(sym): return NIFTY500_STOCKS.get(sym, {})
